CLUSTAL multiple sequence alignment by MUSCLE (3.8)


tr|A0A2C8F4Y7|A0A2C8F4Y7_9BACT      ------------------------------------------------------------
tr|S0G636|S0G636_9DELT              ------------------------------------------------------------
tr|A0A0A7GBY1|A0A0A7GBY1_9EURY      ------------------------------------------------------------
tr|B8FF77|B8FF77_DESAA              ------------------------------------------------------------
tr|B8FF78|B8FF78_DESAA              ------------------------------------------------------------
tr|B8FEM1|B8FEM1_DESAA              ------------------------------------------------------------
tr|A0A0A7GEG9|A0A0A7GEG9_9EURY      ------------------------------------------------------------
tr|A0A101GBX3|A0A101GBX3_9BACT      ----------------MSKIKEKEYMLDPKEVGVELDKPGHPTSKGWSLVTPEMWKFRWS
tr|A0A101GRY1|A0A101GRY1_9FIRM      ----MTTLIEKLEKINNDKKKNSKYMFDPEKAGVSLDKIGQPTSKGWEVVTPEMWKFRFS
tr|A0A085LA19|A0A085LA19_9FIRM      ------------------------MSTAVEEKEKALHEHLEKREYWWWAEKARSSRIDYL
tr|A0A142JYV4|A0A142JYV4_9ZZZZ      --------------------------MAEPAVDKNIKELEKKQQWWWAAEKKRSKRLDYL
tr|A0A2C8EFD1|A0A2C8EFD1_9BACT      ------------------------------------------------------------
tr|A0A142JYV8|A0A142JYV8_9ZZZZ      --------------------------MAEPAKNASIQDLEKKQEWWWAAEKKRSKRLDYL
tr|A0A142JYV6|A0A142JYV6_9ZZZZ      --------------------------MAEPAKNASIQDLEKKQEWWWAAEKKRSKRLDYL
tr|A0A142JYV7|A0A142JYV7_9ZZZZ      --------------------------MAEPAKNNSVAELEKKQEWWWAAEKKRSKRLDYL
tr|W6CHK3|W6CHK3_9DELT              --------------------------MAEPAKNISIQELEKKQEWWWAAEKKRSKRLDYL
tr|A0A099TEH5|A0A099TEH5_9DELT      -------------MKSRKLTRMEEIFMAEPAKNASIQDLEKKQEWWWAAEKKRSKRLDYL
tr|M9T4V0|M9T4V0_9BACT              ------------------------------------------------------------
tr|K7XH43|K7XH43_9BACT              ------------------------------------------------------------
tr|A0A142JYV5|A0A142JYV5_9ZZZZ      ------------------------------------------------------------
tr|A0A094K1W7|A0A094K1W7_9DELT      -----------------MIKRDNNGGYIMAEAAVNIKELEKNQEWWRVAEQKRSKRLDYL
tr|K7WP62|K7WP62_9BACT              ------------------------------------------------------------
tr|D8WZ05|D8WZ05_9DELT              MRLTRTPRSAANCKEVIDILLRRIQWAQAAEARQDIEQLKESQQWWKVAEKLRSPRLDYL
tr|B0CN00|B0CN00_9DELT              ------------------------MTAEPAKLDVSLQEHEENQEWWWIAEKKRSKRLDYL
tr|B8FF75|B8FF75_DESAA              ------------------------MTAEPAKLDVSLQEHEENQEWWWIAEKKRSKRLDYL
tr|B8FEM4|B8FEM4_DESAA              -------------------------MVAEPAQDQSVQELEDKQEWWWVAEKKRSKRLDYL
tr|B0CMZ9|B0CMZ9_9DELT              -----------------------MEMVAEPAQDQSVQELEDKQEWWWVAEKKRSKRLDYL
tr|M9TCC2|M9TCC2_9BACT              ------------------------------------------------------------
tr|M9TCD0|M9TCD0_9BACT              ------------------------------------------------------------
tr|M9T6T1|M9T6T1_9BACT              ------------------------------------------------------------
tr|M9T778|M9T778_9BACT              ------------------------------------------------------------
tr|M9TAN7|M9TAN7_9BACT              ------------------------------------------------------------
tr|M9T734|M9T734_9BACT              ------------------------------------------------------------
tr|M9T740|M9T740_9BACT              ------------------------------------------------------------
tr|M9T6R5|M9T6R5_9BACT              ------------------------------------------------------------
tr|M9T6P1|M9T6P1_9BACT              ------------------------------------------------------------
tr|M9T6S4|M9T6S4_9BACT              ------------------------------------------------------------
tr|M9T6S9|M9T6S9_9BACT              ------------------------------------------------------------
tr|M9TAL9|M9TAL9_9BACT              ------------------------------------------------------------
tr|M9T6Q7|M9T6Q7_9BACT              ------------------------------------------------------------
tr|M9T760|M9T760_9BACT              ------------------------------------------------------------
tr|M9TAP4|M9TAP4_9BACT              ------------------------------------------------------------
tr|M9TCA0|M9TCA0_9BACT              ------------------------------------------------------------
tr|M9TCD4|M9TCD4_9BACT              ------------------------------------------------------------
tr|M9T4U5|M9T4U5_9BACT              ------------------------------------------------------------
                                                                                                

tr|A0A2C8F4Y7|A0A2C8F4Y7_9BACT      ------------------------------------------------------------
tr|S0G636|S0G636_9DELT              ------------------------------------------------------------
tr|A0A0A7GBY1|A0A0A7GBY1_9EURY      ------------------------------------------------------------
tr|B8FF77|B8FF77_DESAA              ------------------------------------------------------------
tr|B8FF78|B8FF78_DESAA              ------------------------------------------------------------
tr|B8FEM1|B8FEM1_DESAA              ------------------------------------------------------------
tr|A0A0A7GEG9|A0A0A7GEG9_9EURY      --------MLVSNVQKPARLSIERAALYTESMKESEG--EPMPVRQAKALKHILENIPIQ
tr|A0A101GBX3|A0A101GBX3_9BACT      IADKVQIPAPQYYSDPDAYIDMTKSLVMKEVLDENPK--LPKAIYSATVTERLLDRQNIK
tr|A0A101GRY1|A0A101GRY1_9FIRM      VADKIGVDAPVYFADKDAYIDMTQFIVFKEIADANPN--DPLAILVAKAYEKVLDTIPMK
tr|A0A085LA19|A0A085LA19_9FIRM      RKAVWPKAAKGSSYLPGTKICWHGYKIYREVFDTPDAKMDPYILTFAKAQAKVLDTIPIF
tr|A0A142JYV4|A0A142JYV4_9ZZZZ      RKAIWKKGAVGGVYPAGLRVDLEQAQIDTDFMRSMEYSPDPHVIRFAKMFANYLDNKTIF
tr|A0A2C8EFD1|A0A2C8EFD1_9BACT      ------------------------------------------------------------
tr|A0A142JYV8|A0A142JYV8_9ZZZZ      RKAIWKKGAIGGLYPAGLQVDLEQAKLHTQASRDMEYSPDPFVVKQAKVFAHYLDNKTIF
tr|A0A142JYV6|A0A142JYV6_9ZZZZ      RKAIWKKGAIGGLYPAGLQVDLEQAVLQTQKARELEASPDPFVVKQAKIFADYLDSKTIF
tr|A0A142JYV7|A0A142JYV7_9ZZZZ      RKGMWKKGAIGGLYPAGLQVDLEQAVLQTQKARELETSPDPFVVKQAKIFADYLDSKTIF
tr|W6CHK3|W6CHK3_9DELT              RKAMWKKGAIGGLYPAGLQVDLEECQLDTAKARELENAPDPYVVKYAKIFAHYLDNKTIF
tr|A0A099TEH5|A0A099TEH5_9DELT      RKAIWKKGAIGGLYPAGLQVDLEQAQLDTAKARELELAPDPYVVKYAKIFANYLDNKTIF
tr|M9T4V0|M9T4V0_9BACT              ------------------------------------------------------------
tr|K7XH43|K7XH43_9BACT              ------------------------------------------------------------
tr|A0A142JYV5|A0A142JYV5_9ZZZZ      ---------------------MERAGLFTDGYFANLN--DPGMVRHAKAVANVLDNITIF
tr|A0A094K1W7|A0A094K1W7_9DELT      RKAVWKKGAVGGLYAPGIKVDLERAGLFTEGYFANLN--DPGMVRHAKAVANVLDNIPIF
tr|K7WP62|K7WP62_9BACT              ------------------------------------------------------------
tr|D8WZ05|D8WZ05_9DELT              RKAVWKKGAIGGAYAPGIKIEIMRNILFTESWKENER--DPIMMRKAKALAHVWRNIPIF
tr|B0CN00|B0CN00_9DELT              RKAVWKKGALGGNYAPGIKVDLEGPKLFTDMWNFWKF--DPIIMRRAKALAHVFDNISIF
tr|B8FF75|B8FF75_DESAA              RKAVWKKGALGGNYAPGIKVDLEGPKLFTDMWNFWKF--DPIIMRRAKALAHVFDNISIF
tr|B8FEM4|B8FEM4_DESAA              RKSIWKKGALGGNYAPGIKLDLECATLFTDMWKFWKY--DPIMMRRAKAIAHVLDKKTIF
tr|B0CMZ9|B0CMZ9_9DELT              RKSIWKKGALGGNYAPGIKLDLECATLFTDMWKFWKY--DPIMMRRAKAIAHVLDKKTIF
tr|M9TCC2|M9TCC2_9BACT              ------------------------------------------------------------
tr|M9TCD0|M9TCD0_9BACT              ------------------------------------------------------------
tr|M9T6T1|M9T6T1_9BACT              ------------------------------------------------------------
tr|M9T778|M9T778_9BACT              ------------------------------------------------------------
tr|M9TAN7|M9TAN7_9BACT              ------------------------------------------------------------
tr|M9T734|M9T734_9BACT              ------------------------------------------------------------
tr|M9T740|M9T740_9BACT              ------------------------------------------------------------
tr|M9T6R5|M9T6R5_9BACT              ------------------------------------------------------------
tr|M9T6P1|M9T6P1_9BACT              ------------------------------------------------------------
tr|M9T6S4|M9T6S4_9BACT              ------------------------------------------------------------
tr|M9T6S9|M9T6S9_9BACT              ------------------------------------------------------------
tr|M9TAL9|M9TAL9_9BACT              ------------------------------------------------------------
tr|M9T6Q7|M9T6Q7_9BACT              ------------------------------------------------------------
tr|M9T760|M9T760_9BACT              ------------------------------------------------------------
tr|M9TAP4|M9TAP4_9BACT              ------------------------------------------------------------
tr|M9TCA0|M9TCA0_9BACT              ------------------------------------------------------------
tr|M9TCD4|M9TCD4_9BACT              ------------------------------------------------------------
tr|M9T4U5|M9T4U5_9BACT              ------------------------------------------------------------
                                                                                                

tr|A0A2C8F4Y7|A0A2C8F4Y7_9BACT      ------------------------------------------------------------
tr|S0G636|S0G636_9DELT              ------------------------------------------------------------
tr|A0A0A7GBY1|A0A0A7GBY1_9EURY      ------------------------------------------------------------
tr|B8FF77|B8FF77_DESAA              ------------------------------------------------------------
tr|B8FF78|B8FF78_DESAA              ------------------------------------------------------------
tr|B8FEM1|B8FEM1_DESAA              ------------------------------------------------------------
tr|A0A0A7GEG9|A0A0A7GEG9_9EURY      ILPGEIIVGTMLPDPPGAILFPEGVGLRIINDLESLPGRESNRLVVDEEDARILVEEIAP
tr|A0A101GBX3|A0A101GBX3_9BACT      LRPYEMLIGMLANDEHAILFDSMNEAWGNIGEAFEKVPEKLWYW--KDGKRVPMTKEEFD
tr|A0A101GRY1|A0A101GRY1_9FIRM      IRPYEMVIGQYSGDEHGMPGDPQKQNWVQVEAAFKNAPDRMKYW--KDGKLVNLSAQEMQ
tr|A0A085LA19|A0A085LA19_9FIRM      IIDQSRIVGYTGSAPHKL-YMTPQSSFNVAWDMYNDRMDLVDRE--EDRPWIKEAIEFMK
tr|A0A142JYV4|A0A142JYV4_9ZZZZ      ITDQAQLVGYVGSLPHTV-AWLPSVGSPLNVEVLNDATVLPEPI--DES--LKVVNDVIA
tr|A0A2C8EFD1|A0A2C8EFD1_9BACT      ------------------------------------------------------------
tr|A0A142JYV8|A0A142JYV8_9ZZZZ      ITDKSQLVGYVGSAPQTI-GWNPTLATILNAEVLNDSTAIPEPL--DDS--IKVINDVIA
tr|A0A142JYV6|A0A142JYV6_9ZZZZ      ITDHAQIVSYVGSLPNTI-GWDPTLATILNAEVLNDSTVIPEPL--DES--LKVINEVIA
tr|A0A142JYV7|A0A142JYV7_9ZZZZ      ITDHAQLVSYVGSLPNTI-NWNPTMATILNAEVINDPTVIPEPL--DES--LKVINEVIA
tr|W6CHK3|W6CHK3_9DELT              ITDKAQLVSYVGSLPNTI-GWNPTTASMVNLEVLNDSSALPEPL--DAS--LKVINEVAA
tr|A0A099TEH5|A0A099TEH5_9DELT      ITDKAQLVGYVGSLPNTI-NWIPSVATMFNLEVLNDSTALPEPL--DAS--LKVINEVSA
tr|M9T4V0|M9T4V0_9BACT              ------------------------------------------------------------
tr|K7XH43|K7XH43_9BACT              ------------------------------------------------------------
tr|A0A142JYV5|A0A142JYV5_9ZZZZ      ITDQAQLVGYVGSLPHTI-SWLIEGGALLNEEVYNEPGIAPEPE--AES--LKKIAAMMD
tr|A0A094K1W7|A0A094K1W7_9DELT      ITDQAQLVGYVGSAPHTI-SWLIEGGSLLNEEVYNEPGIAPEPE--AES--LKKMAAMMD
tr|K7WP62|K7WP62_9BACT              ------------------------------------------------------------
tr|D8WZ05|D8WZ05_9DELT              ITDHAQLVGYVGSAPNTLGMWPIEGASMVNEEAYNEEGVIPEPE--EES--LKIMADLNN
tr|B0CN00|B0CN00_9DELT              ITDHSQIVGYWGSAPHTI-SWRVDGASIVNEELYNEPGIMPEPE--EES--LRKVAEIND
tr|B8FF75|B8FF75_DESAA              ITDHSQIVGYWGSAPHTI-SWRVDGASIVNEELYNEPGIMPEPE--EES--LRKVAEIND
tr|B8FEM4|B8FEM4_DESAA              ITDHAQLVGYFGSLPNTI-MWRVDGASMVNEEAYNEPGIMPEPE--NES--LQKVAELND
tr|B0CMZ9|B0CMZ9_9DELT              ITDHAQLVGYFGSLPNTI-MWRVDGASMVNEEAYNEPGIMPEPE--NES--LQKVAELND
tr|M9TCC2|M9TCC2_9BACT              ------------------------------------------------------------
tr|M9TCD0|M9TCD0_9BACT              ------------------------------------------------------------
tr|M9T6T1|M9T6T1_9BACT              ------------------------------------------------------------
tr|M9T778|M9T778_9BACT              ------------------------------------------------------------
tr|M9TAN7|M9TAN7_9BACT              ------------------------------------------------------------
tr|M9T734|M9T734_9BACT              ------------------------------------------------------------
tr|M9T740|M9T740_9BACT              ------------------------------------------------------------
tr|M9T6R5|M9T6R5_9BACT              ------------------------------------------------------------
tr|M9T6P1|M9T6P1_9BACT              ------------------------------------------------------------
tr|M9T6S4|M9T6S4_9BACT              ------------------------------------------------------------
tr|M9T6S9|M9T6S9_9BACT              ------------------------------------------------------------
tr|M9TAL9|M9TAL9_9BACT              ------------------------------------------------------------
tr|M9T6Q7|M9T6Q7_9BACT              ------------------------------------------------------------
tr|M9T760|M9T760_9BACT              ------------------------------------------------------------
tr|M9TAP4|M9TAP4_9BACT              ------------------------------------------------------------
tr|M9TCA0|M9TCA0_9BACT              ------------------------------------------------------------
tr|M9TCD4|M9TCD4_9BACT              ------------------------------------------------------------
tr|M9T4U5|M9T4U5_9BACT              ------------------------------------------------------------
                                                                                                

tr|A0A2C8F4Y7|A0A2C8F4Y7_9BACT      ---------------------------------RHDHCAPPGSAAGQGGEPHLCLSVAPQ
tr|S0G636|S0G636_9DELT              ------------------------------------------------------------
tr|A0A0A7GBY1|A0A0A7GBY1_9EURY      ------------------------------------------------------------
tr|B8FF77|B8FF77_DESAA              ------------------------------------------------------------
tr|B8FF78|B8FF78_DESAA              ------------------------------------------------------------
tr|B8FEM1|B8FEM1_DESAA              ------------------------------------------------------------
tr|A0A0A7GEG9|A0A0A7GEG9_9EURY      YWESR---------NIEAFASKLMPDIMEVMLSGSLFVLTELAGISHVAVNYPYLL--NR
tr|A0A101GBX3|A0A101GBX3_9BACT      EIKNEIAPKFNCSVRVEPRLTEEERHMYFCPEAPGRYWETFASNGQRANPDHDWYL--HL
tr|A0A101GRY1|A0A101GRY1_9FIRM      ELRDKVGNKYNASNKVIPRLTEQEYHMYFCPEYPGRYAESYGSS-QRASADHDWYM--RL
tr|A0A085LA19|A0A085LA19_9FIRM      PYTYE-----ARADRILSR-----RQRIMCSTSQTFTGSSHRESQTYSTTQWGYFHSG--
tr|A0A142JYV4|A0A142JYV4_9ZZZZ      FWSGK-----ADADRMAPM---ADVEDLTKILSGTIVWGVPLARGGYSGKNYEYFMTGER
tr|A0A2C8EFD1|A0A2C8EFD1_9BACT      ------------------------------------------------------------
tr|A0A142JYV8|A0A142JYV8_9ZZZZ      YWSGK-----ADADRMIPL---ADMTDISKILSGTIGWGVPLARGGYSGKDYEYIMSGKR
tr|A0A142JYV6|A0A142JYV6_9ZZZZ      YWSGK-----GDADRVMPL---VDVSDLMKILSGTIGWGTPMARGGYSGKDYEYIMTGKR
tr|A0A142JYV7|A0A142JYV7_9ZZZZ      YWSGK-----TDADRIMSQ---TDMADIMKILSGTIGWGIPLARGGYSGKDYEYIMSGKR
tr|W6CHK3|W6CHK3_9DELT              YWAGK-----ADADRMMPR---VDMTDVMKVLSGTIGWGSAVARLGYSGKDYEYIMTGKR
tr|A0A099TEH5|A0A099TEH5_9DELT      YWSGK-----ADSDKMMPR---VDMPDVMKVLSGTIGWGAAIARMGYSGKDYEYIMTGKR
tr|M9T4V0|M9T4V0_9BACT              ------------------------------------------------------------
tr|K7XH43|K7XH43_9BACT              ------------------------------------------------------------
tr|A0A142JYV5|A0A142JYV5_9ZZZZ      RWNGH-----TVQDKFIPYVLSFAAEEGVKLLSGAVGWGLPLSISGYNGKDYEYILTGKR
tr|A0A094K1W7|A0A094K1W7_9DELT      KWNGY-----SVQDRFIPYVLSFAAEEGVKLLSGAVGWGLPISISGYNGKDYEYILTAKR
tr|K7WP62|K7WP62_9BACT              ------------------------------------------------------------
tr|D8WZ05|D8WZ05_9DELT              YWAGN-----TAIDQVARL---LDPEDAVKFMSGAIGWGVPTSAYGYSGKDYEYILTGKR
tr|B0CN00|B0CN00_9DELT              YWAGQ-----TAVDKVARI---LDPEDAVKFLSGAIGWGAPTSAYGYSGKNYEYYLKGER
tr|B8FF75|B8FF75_DESAA              YWAGQ-----TAVDKVARI---LDPEDAVKFLSGAIGWGAPTSAYGYSGKNYEYYLKGER
tr|B8FEM4|B8FEM4_DESAA              YWAGQ-----TAVDKVARI---LDPEDAVKFLSGAIGWGAPSSAYGYSGKDYEYLFAGRR
tr|B0CMZ9|B0CMZ9_9DELT              YWAGQ-----TAVDKVARI---LDPEDAVKFLSGAIGWGAPSSAYGYSGKDYEYLFAGRR
tr|M9TCC2|M9TCC2_9BACT              ------------------------------------------------------------
tr|M9TCD0|M9TCD0_9BACT              ------------------------------------------------------------
tr|M9T6T1|M9T6T1_9BACT              ------------------------------------------------------------
tr|M9T778|M9T778_9BACT              ------------------------------------------------------------
tr|M9TAN7|M9TAN7_9BACT              ------------------------------------------------------------
tr|M9T734|M9T734_9BACT              ------------------------------------------------------------
tr|M9T740|M9T740_9BACT              ------------------------------------------------------------
tr|M9T6R5|M9T6R5_9BACT              ------------------------------------------------------------
tr|M9T6P1|M9T6P1_9BACT              ------------------------------------------------------------
tr|M9T6S4|M9T6S4_9BACT              ------------------------------------------------------------
tr|M9T6S9|M9T6S9_9BACT              ------------------------------------------------------------
tr|M9TAL9|M9TAL9_9BACT              ------------------------------------------------------------
tr|M9T6Q7|M9T6Q7_9BACT              ------------------------------------------------------------
tr|M9T760|M9T760_9BACT              ------------------------------------------------------------
tr|M9TAP4|M9TAP4_9BACT              ------------------------------------------------------------
tr|M9TCA0|M9TCA0_9BACT              ------------------------------------------------------------
tr|M9TCD4|M9TCD4_9BACT              ------------------------------------------------------------
tr|M9T4U5|M9T4U5_9BACT              ------------------------------------------------------------
                                                                                                

tr|A0A2C8F4Y7|A0A2C8F4Y7_9BACT      G-----------------------------------------------------------
tr|S0G636|S0G636_9DELT              ------------------------------------------------------------
tr|A0A0A7GBY1|A0A0A7GBY1_9EURY      ------------------------------------------------------------
tr|B8FF77|B8FF77_DESAA              ------------------------------------------------------------
tr|B8FF78|B8FF78_DESAA              ------------------------------------------------------------
tr|B8FEM1|B8FEM1_DESAA              ------------------------------------------------------------
tr|A0A0A7GEG9|A0A0A7GEG9_9EURY      GFRWFVEESERRIAEIRESGCEDAE--------------KLVFYEATKITAEGMTRFAER
tr|A0A101GBX3|A0A101GBX3_9BACT      GLRKLIEMKREKLEQYERELELVGKEETADYKKVEGLKEKIDNAKAGIQVAEAVVRWIKR
tr|A0A101GRY1|A0A101GRY1_9FIRM      GWRKLVEMKREKLKEYEKEYEGIRVSEPMDYHKTDEVLNKITNAKAQIRVGEAVIRWFKR
tr|A0A085LA19|A0A085LA19_9FIRM      -FNNILAQVNENIAEAEKVLYEVGARP--DFPAEYDALNKLDNWRSFKIVIEAMLRWAKR
tr|A0A142JYV4|A0A142JYV4_9ZZZZ      AFEDIIAELDKNLDDAYDLVHSPFASK--EISETYP---KMVTWEAMQICLRAGIRFGQR
tr|A0A2C8EFD1|A0A2C8EFD1_9BACT      ------------------------------------------------------------
tr|A0A142JYV8|A0A142JYV8_9ZZZZ      AFEDVLAEINKNLDEADAKAHEPGANE--EITALYK---KMVNWEAMAITLEACIRHGQR
tr|A0A142JYV6|A0A142JYV6_9ZZZZ      AFEDVLAEIDKNLDEADANAHEPTANQ--EIIKLYE---KMNNWEAYKITLEAGIRHAQR
tr|A0A142JYV7|A0A142JYV7_9ZZZZ      AFEDVLAEIDKNLDEADASAHEPTANQ--EIIKLYE---KMNNWEAYKIALEACIRHGQR
tr|W6CHK3|W6CHK3_9DELT              GFEDVIAEIDENMDKADAQAHMPAANK--EIGALYD---KMNTWEAMKITLEAGIRHAQR
tr|A0A099TEH5|A0A099TEH5_9DELT      GFEGVITELNSQIDKADAEAHEPKAGK--KISDLYD---KMNTWEAMKITLEACIRHGQR
tr|M9T4V0|M9T4V0_9BACT              ------------------------------------------------------------
tr|K7XH43|K7XH43_9BACT              ------------------------------------------------------------
tr|A0A142JYV5|A0A142JYV5_9ZZZZ      GFEDIIEDIDRRQNDMTEKARK-KAGP--EYLHVGL---RMMNWEGMKIVLQAVIRYANR
tr|A0A094K1W7|A0A094K1W7_9DELT      GFEDIIAEIDRRQEDMKDKARK-KAGP--EYLHVGS---RMMNWEGMKIALQAVIRYANR
tr|K7WP62|K7WP62_9BACT              ------------------------------------------------------------
tr|D8WZ05|D8WZ05_9DELT              GFEDIMEEIEARLDEAQEIVRG-TPGP--ELLPYYE---KIQNWEAMLIVLEAAVDWARR
tr|B0CN00|B0CN00_9DELT              GFEDIIADIEDHIAEAEEKTIG-TPGP--DILPIYD---RIQNWEAMITVLEAAIRFAKR
tr|B8FF75|B8FF75_DESAA              GFEDIIADIEDHIAEAEEKTIG-TPGP--DILPIYD---RIQNWEAMITVLEAAIRFAKR
tr|B8FEM4|B8FEM4_DESAA              GFEDIIEEINAAIEKAEDKTVG-VPGP--EILDIYD---RLQNWDAMILVLEAGIRHAKR
tr|B0CMZ9|B0CMZ9_9DELT              GFEDIIEEINAAIEKAEDKTVG-VPGP--EILDIYD---RLQNWDAMILVLEAGIRHAKR
tr|M9TCC2|M9TCC2_9BACT              ------------------------------------------------------------
tr|M9TCD0|M9TCD0_9BACT              ------------------------------------------------------------
tr|M9T6T1|M9T6T1_9BACT              ------------------------------------------------------------
tr|M9T778|M9T778_9BACT              ------------------------------------------------------------
tr|M9TAN7|M9TAN7_9BACT              ------------------------------------------------------------
tr|M9T734|M9T734_9BACT              ------------------------------------------------------------
tr|M9T740|M9T740_9BACT              ------------------------------------------------------------
tr|M9T6R5|M9T6R5_9BACT              ------------------------------------------------------------
tr|M9T6P1|M9T6P1_9BACT              ------------------------------------------------------------
tr|M9T6S4|M9T6S4_9BACT              ------------------------------------------------------------
tr|M9T6S9|M9T6S9_9BACT              ------------------------------------------------------------
tr|M9TAL9|M9TAL9_9BACT              ------------------------------------------------------------
tr|M9T6Q7|M9T6Q7_9BACT              ------------------------------------------------------------
tr|M9T760|M9T760_9BACT              ------------------------------------------------------------
tr|M9TAP4|M9TAP4_9BACT              ------------------------------------------------------------
tr|M9TCA0|M9TCA0_9BACT              ------------------------------------------------------------
tr|M9TCD4|M9TCD4_9BACT              ------------------------------------------------------------
tr|M9T4U5|M9T4U5_9BACT              ------------------------------------------------------------
                                                                                                

tr|A0A2C8F4Y7|A0A2C8F4Y7_9BACT      ------------------------------------------------------------
tr|S0G636|S0G636_9DELT              ------------------------------------------------------------
tr|A0A0A7GBY1|A0A0A7GBY1_9EURY      ------------------------------------------------------------
tr|B8FF77|B8FF77_DESAA              ------------------------------------------------------------
tr|B8FF78|B8FF78_DESAA              ------------------------------------------------------------
tr|B8FEM1|B8FEM1_DESAA              ------------------------------------------------------------
tr|A0A0A7GEG9|A0A0A7GEG9_9EURY      YAGLARNMAEE-EGDEARREELIRIAEICERVPAEPPESFHEAVQFVWFVQCALHQENYE
tr|A0A101GBX3|A0A101GBX3_9BACT      QAEVARKAAPQM-PDEKSKKIAEQVAKNCDWVAENVPRTFWEALQLYWSVFCVYYGIEAV
tr|A0A101GRY1|A0A101GRY1_9FIRM      LAEAVRKAAPQM-PDEKARLIAEQAAANCDWVAENVPRTFWEAVQMFWGSYCIFRGLEA-
tr|A0A085LA19|A0A085LA19_9FIRM      YSRLAKIIAENFETDPQRKQELMEISRICAKVPGEAPESYHEFLM-YDNMAQRAKRYEWG
tr|A0A142JYV4|A0A142JYV4_9ZZZZ      YARLARIIAENYETDNKRKEELLQIADCCERVPAKPPRTLQESLQ-YDLFTQVFSRSEAI
tr|A0A2C8EFD1|A0A2C8EFD1_9BACT      ------------------------------------------------------------
tr|A0A142JYV8|A0A142JYV8_9ZZZZ      FARLARIIAENYETDNKRKEELLQIADCCESVPAKTPRTLQESLQ-YDLFIQLFSRSEAI
tr|A0A142JYV6|A0A142JYV6_9ZZZZ      YARLAKIIAENYETDNKRKEELLQIADCCERVPAKPPRTLQESLQ-YDLFIQLFSRSEAI
tr|A0A142JYV7|A0A142JYV7_9ZZZZ      YARLARIIAENYETDNKRKEELLQIADCCERVPAKTPRTLQESLQ-YDLFIQLFSRTEAV
tr|W6CHK3|W6CHK3_9DELT              YARLARIIAENFETDNKRKEELLQIANCCERVPAKPPRTLQESLQ-YDLFIQNFSRTEAV
tr|A0A099TEH5|A0A099TEH5_9DELT      FARLARIIAENYETDNKRKEELLQLADCCERVPAKPPRTLQESLQ-YDLFIQLFSRSEAL
tr|M9T4V0|M9T4V0_9BACT              ------------------------------------------------------------
tr|K7XH43|K7XH43_9BACT              ------------------------------------------------------------
tr|A0A142JYV5|A0A142JYV5_9ZZZZ      YARLAKIVAENYETNPKCREELLRIAETCERVPAKPQRNLQESLQ-FDHFLQVVERFESG
tr|A0A094K1W7|A0A094K1W7_9DELT      YARLAKIVAENYETDPKRREELLRIAETCERVPAKPQRNLQESLQ-FDHFLQVVERFESG
tr|K7WP62|K7WP62_9BACT              ------------------------------------------------------------
tr|D8WZ05|D8WZ05_9DELT              YARLARIIAENFESDPKRKEELLRIAETCERVPAKAPRSLQESLQ-MDHFIQILARYEAY
tr|B0CN00|B0CN00_9DELT              YARLARTMAEHLETDEKRKEELLRIAETCERVPAKAPRNLQESFQ-MDMLIQTMCRFEAS
tr|B8FF75|B8FF75_DESAA              YARLARTMAEHLETDEKRKEELLRIAETCERVPAKAPRNLQESFQ-MDMLIQTMCRFEAS
tr|B8FEM4|B8FEM4_DESAA              YARLARTMAENMETDEKRREELLKIAETCERVPARAPRNLQESLQ-YDHFIQIFARTEAH
tr|B0CMZ9|B0CMZ9_9DELT              YARLARTMAENMETDEKRREELLKIAETCERVPARAPRNLQESLQ-YDHFIQIFARTEAH
tr|M9TCC2|M9TCC2_9BACT              ------------------------------------------------------------
tr|M9TCD0|M9TCD0_9BACT              ------------------------------------------------------------
tr|M9T6T1|M9T6T1_9BACT              ------------------------------------------------------------
tr|M9T778|M9T778_9BACT              ------------------------------------------------------------
tr|M9TAN7|M9TAN7_9BACT              ------------------------------------------------------------
tr|M9T734|M9T734_9BACT              ------------------------------------------------------------
tr|M9T740|M9T740_9BACT              ------------------------------------------------------------
tr|M9T6R5|M9T6R5_9BACT              ------------------------------------------------------------
tr|M9T6P1|M9T6P1_9BACT              ------------------------------------------------------------
tr|M9T6S4|M9T6S4_9BACT              ------------------------------------------------------------
tr|M9T6S9|M9T6S9_9BACT              ------------------------------------------------------------
tr|M9TAL9|M9TAL9_9BACT              ------------------------------------------------------------
tr|M9T6Q7|M9T6Q7_9BACT              ------------------------------------------------------------
tr|M9T760|M9T760_9BACT              ------------------------------------------------------------
tr|M9TAP4|M9TAP4_9BACT              ------------------------------------------------------------
tr|M9TCA0|M9TCA0_9BACT              ------------------------------------------------------------
tr|M9TCD4|M9TCD4_9BACT              ------------------------------------------------------------
tr|M9T4U5|M9T4U5_9BACT              ------------------------------------------------------------
                                                                                                

tr|A0A2C8F4Y7|A0A2C8F4Y7_9BACT      ------------------------------------------------------------
tr|S0G636|S0G636_9DELT              ------------------------------------------------------------
tr|A0A0A7GBY1|A0A0A7GBY1_9EURY      ------------------------------------------------------------
tr|B8FF77|B8FF77_DESAA              ------------------------------------------------------------
tr|B8FF78|B8FF78_DESAA              ------------------------------------------------------------
tr|B8FEM1|B8FEM1_DESAA              ------------------------------------------------------------
tr|A0A0A7GEG9|A0A0A7GEG9_9EURY      QGISMGRIDQYLLPYYLKDL-REGRIDRKKAFEILANLWVKPNEIVP---PFDSLLELYF
tr|A0A101GBX3|A0A101GBX3_9BACT      CHTGAFKQDRSFWPWFEKDVIKEKTLDRVTAAELLACWAAKYHETSGYS-GRFGSMGKSG
tr|A0A101GRY1|A0A101GRY1_9FIRM      CHPGCFKPDALFWEWYERDVVKEKTLDRNLAGEVLASIASKYHETAGFGMTRFGGLGKSG
tr|A0A085LA19|A0A085LA19_9FIRM      EGAWPAKPDTWGWPCYKKDVIDEKTLSQDDALDLTCEYLIRAFEYGNPR-NRQYRELM--
tr|A0A142JYV4|A0A142JYV4_9ZZZZ      EGAWPARPDYYHGPYYDKDVNIEKRISREDALDLVGEFLIRAHEVSQYK-PKWVREGL--
tr|A0A2C8EFD1|A0A2C8EFD1_9BACT      ------------------------------------------------------------
tr|A0A142JYV8|A0A142JYV8_9ZZZZ      EGAWPARPDYYHGPYYEKDVNIDKRITKEEALDLVGEFLIRAAEVSQYK-PKWVREGL--
tr|A0A142JYV6|A0A142JYV6_9ZZZZ      EGAWPARPDYYHGPYYEKDVNIDKRITKEAALDLVGEFLIRAAEVSQYK-VKWVREGL--
tr|A0A142JYV7|A0A142JYV7_9ZZZZ      EGAWPARPDYYHGPYYEKDVNIDKRITKEEALDLAGEFLIRAAEVSQYK-VKWVREGL--
tr|W6CHK3|W6CHK3_9DELT              EGSWPARPDYYHGQYYDKDVNIDKRITKEEAMDLVGEFLIRAAEVSQYK-PKWAREGL--
tr|A0A099TEH5|A0A099TEH5_9DELT      EGAWPARPDYYHGPYYDKDVNIDKRITKEEALDLAGEFLIRAAEVCQYK-PKWAREGL--
tr|M9T4V0|M9T4V0_9BACT              ------------------------------------------------------------
tr|K7XH43|K7XH43_9BACT              ------------------------------------------------------------
tr|A0A142JYV5|A0A142JYV5_9ZZZZ      GGAWPSRPDYYHGPWYDKDVNIDKRLTKEEALDLVGEFMIRAHEVGAFF-PRWTREGL--
tr|A0A094K1W7|A0A094K1W7_9DELT      GGAWPSRPDYYHGSWYDKDVNIDKRLTKEEALDLVGEFMIRAHEVGSFF-PRWTREGL--
tr|K7WP62|K7WP62_9BACT              ------------------------------------------------------------
tr|D8WZ05|D8WZ05_9DELT              EGAWPARPDYYHGPFYDKDVNIEKNLTREEALDLVGEFLIRTYEVGGFG-PRWGREGL--
tr|B0CN00|B0CN00_9DELT              EGAWPARPDYYHGPFYEKDVLQDKTLTEEEATDLIGEFMIRAYEVGGFG-PRWAREGM--
tr|B8FF75|B8FF75_DESAA              EGAWPARPDYYHGPFYEKDVLQDKTLTEEEATDLIGEFMIRAYEVGGFG-PRWAREGM--
tr|B8FEM4|B8FEM4_DESAA              EGAWPARPDYYHGPYYDKDVNVDKTLTKEDALDLVGEFMIRAYEVGGFA-PRWAREGL--
tr|B0CMZ9|B0CMZ9_9DELT              EGAWPARPDYYHGPYYDKDVNVDKTLTKEDALDLVGEFMIRAYEVGGFA-PRWAREGL--
tr|M9TCC2|M9TCC2_9BACT              ------------------------------------------------------------
tr|M9TCD0|M9TCD0_9BACT              ------------------------------------------------------------
tr|M9T6T1|M9T6T1_9BACT              ------------------------------------------------------------
tr|M9T778|M9T778_9BACT              ------------------------------------------------------------
tr|M9TAN7|M9TAN7_9BACT              ------------------------------------------------------------
tr|M9T734|M9T734_9BACT              ------------------------------------------------------------
tr|M9T740|M9T740_9BACT              ------------------------------------------------------------
tr|M9T6R5|M9T6R5_9BACT              ------------------------------------------------------------
tr|M9T6P1|M9T6P1_9BACT              ------------------------------------------------------------
tr|M9T6S4|M9T6S4_9BACT              ------------------------------------------------------------
tr|M9T6S9|M9T6S9_9BACT              ------------------------------------------------------------
tr|M9TAL9|M9TAL9_9BACT              ------------------------------------------------------------
tr|M9T6Q7|M9T6Q7_9BACT              ------------------------------------------------------------
tr|M9T760|M9T760_9BACT              ------------------------------------------------------------
tr|M9TAP4|M9TAP4_9BACT              ------------------------------------------------------------
tr|M9TCA0|M9TCA0_9BACT              ------------------------------------------------------------
tr|M9TCD4|M9TCD4_9BACT              ------------------------------------------------------------
tr|M9T4U5|M9T4U5_9BACT              ------------------------------------------------------------
                                                                                                

tr|A0A2C8F4Y7|A0A2C8F4Y7_9BACT      --------------STDGGHAGGSLMSASRQGSRL-----PVHAWRTDPVIVANAMQLAR
tr|S0G636|S0G636_9DELT              -----------------MTISDSDIKHLVTHIQHFSVNDGPGIRTTVFLK---GCPLNCA
tr|A0A0A7GBY1|A0A0A7GBY1_9EURY      ------------------------MKGRIFRIQRFSIHDGPGIRTTIFLK---GCPLRCV
tr|B8FF77|B8FF77_DESAA              -------------------MEPGKTIGIVNDIQRMSTNDGPGFRTTVFLK---GCLLDCK
tr|B8FF78|B8FF78_DESAA              ----------------------MAETCLITEIQRFAVNDGPGIRTNVFLK---GCPLKCA
tr|B8FEM1|B8FEM1_DESAA              ----------------------MANACLITEIQRFAINDGPGFRTNVFLK---GCPLKCV
tr|A0A0A7GEG9|A0A0A7GEG9_9EURY      SGQATNQALTIGGVDGSGSDATNELSYLMLEVTKAIPLRQPNVHVRVSSKTPDSFLEMLA
tr|A0A101GBX3|A0A101GBX3_9BACT      QGTRDYSVWTIGGQDKYGKDATNELTRLMLDVWDGYRLHFPDLKFRWFPGTKRDDLKRVC
tr|A0A101GRY1|A0A101GRY1_9FIRM      QGTRDYTVWTLGGQDAHGKDATNDLTRLILDVWDGYRLHFPDLKFRWFPGTKKDDFRRVC
tr|A0A085LA19|A0A085LA19_9FIRM      TGDPGPYVWALGGILPDGSDGANELSDTILKAARLVRVASPTYALRYHPKIRTETLRQAF
tr|A0A142JYV4|A0A142JYV4_9ZZZZ      QGIEGTWVWTLGGVKKDGSDACNDMTVALLQAARLVRVSNPTFGFRWHPMVKDEVLRECF
tr|A0A2C8EFD1|A0A2C8EFD1_9BACT      ---------------------CNGMTIALLQAARLVRVANPTFAFRWHPKVSDEVMRECF
tr|A0A142JYV8|A0A142JYV8_9ZZZZ      QGIEGTWVWTLGGVNEHGDDACNGMTTALLQAARLVRVANPTFGFRWHPKVKEEVLRECF
tr|A0A142JYV6|A0A142JYV6_9ZZZZ      QGIEGTWVWTLGGVNQHGDDACNGMTTALLQAARLVRVANPTFSFRWHPKVKEEVLRECF
tr|A0A142JYV7|A0A142JYV7_9ZZZZ      QGIEGTWVWTLGGVNQHGDDACNGMTTALLQAARLVRVSNPTFGFRWHPKVKEEVLRECF
tr|W6CHK3|W6CHK3_9DELT              QGIEGTWVWTLGGVKQDGSDACNDMTIALLQAARLVRVANPTFSFRWHPKVKEEVLRECF
tr|A0A099TEH5|A0A099TEH5_9DELT      QGIDGTWVWTLGGVKKDGSDACNDMTIALLQAARLVRVANPTFSFRWHPKVKEDVLRECF
tr|M9T4V0|M9T4V0_9BACT              -----------------------DMTDAILKAARLVRVSNPTFAFRWHPQVKDEVMREIF
tr|K7XH43|K7XH43_9BACT              ---------------------CNGMTIALLRAARLVRVSNPTFAFRWHPQVKDEVMREIF
tr|A0A142JYV5|A0A142JYV5_9ZZZZ      QGITGTWVWTLGGVKQDGTDACNDMTIAMLQAARLVRVSNPTFAFRWHPQVKDEVMRECF
tr|A0A094K1W7|A0A094K1W7_9DELT      QGITGTWVWTLGGVKQDGADACNDLTVAFLQAARLVRVSNPTFAFRWHPQVKDEVMRECF
tr|K7WP62|K7WP62_9BACT              -------------------DACNDLTTAFMQAARLVRTANPTFAFRWHPKVKDEVMRECF
tr|D8WZ05|D8WZ05_9DELT              QGITGTWVWTIGGVKPDGTDACNDLTRAFLQAARLVRVANPTFAFRWHPKVPDDIMRECF
tr|B0CN00|B0CN00_9DELT              QGITGTWVWTIGGVKPDGSDACNALTTAFLRTARLIRVSNPTFAFRWHPKVSDEVMRECF
tr|B8FF75|B8FF75_DESAA              QGITGTWVWTIGGVKPDGSDACNALTTAFLRTARLIRVSNPTFAFRWHPKVSDEVMRECF
tr|B8FEM4|B8FEM4_DESAA              QGITGTWVWTLGGVNKDGSDACNDLTVAFLQAARLVRVSNPTFGFRWHPKVKDEVLRECF
tr|B0CMZ9|B0CMZ9_9DELT              QGITGTWVWTLGGVNKDGSDACNDLTVAFLQAARLVRVSNPTFGFRWHPKVKDEVLRECF
tr|M9TCC2|M9TCC2_9BACT              -----------------------DMTDAILQAARLVRVSNPTFGFRWHPKVSDEVMRECF
tr|M9TCD0|M9TCD0_9BACT              -----------------------DMTDAILQAARLVRVSNPTFGFRWHPKVSDEVMRECF
tr|M9T6T1|M9T6T1_9BACT              -----------------------DMTDAILQAARLVRVSNPTFGFRWHPKVKDEVMRECF
tr|M9T778|M9T778_9BACT              -----------------------DMTDAILQAARLVRVSNPTFGFRWHPKVKDEVMRECF
tr|M9TAN7|M9TAN7_9BACT              -----------------------DMTDAILQAARLVRVSNPTFGFRWHPKVKDEVMRECF
tr|M9T734|M9T734_9BACT              -----------------------DMTDAILQAARLVRVSNPTFGFRWHPKVKDEVMRECF
tr|M9T740|M9T740_9BACT              -----------------------DMTDAILQAARLVRVSNPTFGFRWHPKVKDEVMRECF
tr|M9T6R5|M9T6R5_9BACT              -----------------------DMTDAILQAARLVRVSNPTFGFRWHPKVKDEVMRECF
tr|M9T6P1|M9T6P1_9BACT              -----------------------DMTDAILQAARLVRVSNPTFGFRWHPKVKDEVMRECF
tr|M9T6S4|M9T6S4_9BACT              -----------------------DMTDAILQAARLVRVSNPTFGFRWHPKVKDEVMRECF
tr|M9T6S9|M9T6S9_9BACT              -----------------------DMTDAILQAARLVRVSNPTFGFRWHPKVKDEVMRECF
tr|M9TAL9|M9TAL9_9BACT              -----------------------DMTDAILQAARLVRVSNPTSGFRWHPKVKDEVMRECF
tr|M9T6Q7|M9T6Q7_9BACT              -----------------------DMTDAILQAARLVRVSNPTFGFRWHPKVKDEVMRECF
tr|M9T760|M9T760_9BACT              -----------------------DMTDAILQAARLVRVSNPTFGFRWHPKVKDEVMRECF
tr|M9TAP4|M9TAP4_9BACT              -----------------------DMTDAILQAARLVRVSNPTFGFRWHPKVRDEVMRECF
tr|M9TCA0|M9TCA0_9BACT              -----------------------DMTDAILQAARLVRVSNPTFGFRWHPKVKDEVMRECF
tr|M9TCD4|M9TCD4_9BACT              -----------------------DMTDAILQAARLVRVSNPTFGFRWHPKVKDEVLRECF
tr|M9T4U5|M9T4U5_9BACT              -----------------------DMTDAILQAARLVRVSNPTFGFRWHPKVSDEVMRECF
                                                                            *                   

tr|A0A2C8F4Y7|A0A2C8F4Y7_9BACT      PPRRGGTALGAPGVHVAVAGHQAWIPAHAHGQRHGQLRQDHRVRVHQ--RVRPRGE----
tr|S0G636|S0G636_9DELT              WC-------------HNPENIHTFQEFFYHEDKC----VKCG-------DCAEHCPENVI
tr|A0A0A7GBY1|A0A0A7GBY1_9EURY      WCHNPE------SQRFEAEIA-------YRAEKC----TSCH-------RCVAACPANAL
tr|B8FF77|B8FF77_DESAA              WCHNPE------GRRRFPEVI-------PFYTNC----IGCG-------DCVEACA----
tr|B8FF78|B8FF78_DESAA              WC-------------HNPETISAKPQVFWKKRLC----VQCG-------ACMDACP----
tr|B8FEM1|B8FEM1_DESAA              WC-------------HNPETIDAKAQVFWKKRLC----VQCG-------ACMEACP----
tr|A0A0A7GEG9|A0A0A7GEG9_9EURY      GIIAEG--KNNVGIFNDEAVFR---ALRFAGV------EEGDAWNYSTIGCVEISP----
tr|A0A101GBX3|A0A101GBX3_9BACT      EVARTG--LGLPSLRNDLTAIPSLLDMYPGELTL----EQAREWGII--GCNTPGS----
tr|A0A101GRY1|A0A101GRY1_9FIRM      EVIRTG--LGLPSLRNDPLAIETLLSQYPGEFTL----EQARQWGIV--GCNTPGV----
tr|A0A085LA19|A0A085LA19_9FIRM      ECIRHG--LGYPNIRHDDVLVQS--NMYWSGTPL----EEARTWTAQ--ACIVPCP----
tr|A0A142JYV4|A0A142JYV4_9ZZZZ      ECIRQG--LGYPSMRHDPILIAN--TMHWYGHPI----EEARTWVHQ--ACMSPCP----
tr|A0A2C8EFD1|A0A2C8EFD1_9BACT      ECIRQG--LGYPSMRNDPVLVAN--AMHWHGHPV----EEARLWVHQ--ACMSPSP----
tr|A0A142JYV8|A0A142JYV8_9ZZZZ      ECIRQG--LGYPSMRNDPLLISN--SMYWHGHPI----EEARLWVHQ--ACMSPSP----
tr|A0A142JYV6|A0A142JYV6_9ZZZZ      ECIRQG--LGYPSMRNDPLLIAN--SMYWHGHPI----EEARTWVHQ--ACMSPSP----
tr|A0A142JYV7|A0A142JYV7_9ZZZZ      ECIRQG--LGYPSMRNDPLLIAN--SMYWHGHPI----EEARTWVHQ--ACMSPCP----
tr|W6CHK3|W6CHK3_9DELT              ECIRQG--LGYPSMRNDPLLIAN--SMHWHGHPI----EEARTWVHQ--ACMSPCP----
tr|A0A099TEH5|A0A099TEH5_9DELT      ECIRQG--LGYPSMRNDPVLIAN--SMNWHGHPI----EEARTWVHQ--ACMSPCP----
tr|M9T4V0|M9T4V0_9BACT              ECIRHG--LGYPAMRNDPVLIAN--GMHWHGHPL----EEMRTWVHQ--ACMSPCP----
tr|K7XH43|K7XH43_9BACT              ECIRHG--LGYPSMRNDPVLIAN--AMHWHKHPL----EEARTWVHQ--ACMSPCP----
tr|A0A142JYV5|A0A142JYV5_9ZZZZ      ECIRQG--LGYPSMRNDPVLITN--AMHWHGHPI----EEARTWVHQ--ACMSPCP----
tr|A0A094K1W7|A0A094K1W7_9DELT      ECIRQG--LGYPSMRNDPVLITN--VMHWHGHPI----EEARTWVHQ--ACMSPCP----
tr|K7WP62|K7WP62_9BACT              ECIRHG--LGYPSMRNDPILVAN--AMNWHGHPI----EEARTWVHQ--ACMSPCP----
tr|D8WZ05|D8WZ05_9DELT              ECIRHG--LGYPSMRNDPILVQN--AMYWHGHPL----EEARTWVHQ--ACMSPCP----
tr|B0CN00|B0CN00_9DELT              ECIRHG--LGYPSFRHDPILVAN--CMNWHGHPV----EEARTWVHQ--ACMSPCP----
tr|B8FF75|B8FF75_DESAA              ECIRHG--LGYPSFRHDPILVAN--CMNWHGHPV----EEARTWVHQ--ACMSPCP----
tr|B8FEM4|B8FEM4_DESAA              ECIRHG--LGYPSMRNDPLLIQN--AMHWHGHPL----EEARTWVHQ--ACMSPCP----
tr|B0CMZ9|B0CMZ9_9DELT              ECIRHG--LGYPSMRNDPLLIQN--AMHWHGHPL----EEARTWVHQ--ACMSPCP----
tr|M9TCC2|M9TCC2_9BACT              ECIRHG--LGYPSMRNDPVLVQN--TTHWYGHPV----EEARLWVHQ--ACMSPCP----
tr|M9TCD0|M9TCD0_9BACT              ECIRHG--LGYPSMRNDPVLVQN--TTHWYGHPV----EEARLWVHQ--ACMSPCP----
tr|M9T6T1|M9T6T1_9BACT              ECIRHG--LGYPAMRNDPVLVQN--STHWHGHPV----KEARLWVHQ--ACMSPCP----
tr|M9T778|M9T778_9BACT              ECIRHG--LGYPAMRNDPVLVQN--STHWHGHPV----EEARLWVHQ--ACMSPCP----
tr|M9TAN7|M9TAN7_9BACT              ECIRHG--LGYPAMRNDPVLVQN--STHWHGHPV----EEARLWVHQ--ACMSPCP----
tr|M9T734|M9T734_9BACT              ECIRHG--LGYPAMRNDPVLVQN--STHWHGHPV----EEARLWVHQ--ACMSPCP----
tr|M9T740|M9T740_9BACT              ECIRHG--LGYPAMRNDPVLVQN--STHWHGHPV----EEARLWVHQ--ACMSPCP----
tr|M9T6R5|M9T6R5_9BACT              ECIRHG--LGYPAMRNDPVLVQN--STHWHGHPV----EEARLWVHQ--ACMSPCP----
tr|M9T6P1|M9T6P1_9BACT              ECIRHG--LGYPAMRNDPVLVQN--STHWHGHPV----EEARLWVHQ--ACMSPCP----
tr|M9T6S4|M9T6S4_9BACT              ECIRHG--LGYPAMRNDPVLVQN--STHWHGHPV----EEARLWVHQ--ACMSPCP----
tr|M9T6S9|M9T6S9_9BACT              ECIRHG--LGYPAMRNDPVLVQN--STHWHGHPV----EEARLWVYQ--ACMSPCP----
tr|M9TAL9|M9TAL9_9BACT              ECIRHG--LGYPAMRNDPVLVQN--STHWHGHPV----EEARLWVHQ--ACMSPCP----
tr|M9T6Q7|M9T6Q7_9BACT              ECIRHG--LGYPAMRNDPVLVQN--STHWHGHPV----EEARLWVHQ--ACMSPCP----
tr|M9T760|M9T760_9BACT              ECIRHG--LGYPAMRNDPVLVQN--STHWHGHPV----EEARLWVHQ--ACMSPCP----
tr|M9TAP4|M9TAP4_9BACT              ECIRHG--LGYPAMRNDPVLVQN--STHWHGHPV----EEARLWVHQ--ACMSPCP----
tr|M9TCA0|M9TCA0_9BACT              ECIRHG--LGYPAMRNDPVLVQN--STHWHGHPV----EEARLWVHQ--ACMSPCP----
tr|M9TCD4|M9TCD4_9BACT              ECIRQG--LGYPSMRNDPILVQN--AMHWHGHPL----EEARLWVHQ--ACMSPCP----
tr|M9T4U5|M9T4U5_9BACT              ECIRHG--LGYPSMRNDPVLVQN--AMHWHGHPL----EEARLWVHQ--ACMSPCP----
                                                                                                

tr|A0A2C8F4Y7|A0A2C8F4Y7_9BACT      -P-------------------------------------------------ADRRRD-AA
tr|S0G636|S0G636_9DELT              IPPRIQYVENPVQSVRFGDGDGSIPTSLRGHHPPPAFSVEKEIEAIDPPRIDREKCTRCM
tr|A0A0A7GBY1|A0A0A7GBY1_9EURY      KP------------ESSGI------------------------------EVDRDVCNGCG
tr|B8FF77|B8FF77_DESAA              -AGAL---------SLNGD--------------------------AKPVIDRALCTD-CF
tr|B8FF78|B8FF78_DESAA              -TGAVQPPIDPVLSQAEGT---------------------------DYYKIDLDRCDYSL
tr|B8FEM1|B8FEM1_DESAA              -TEAIQPPIDPVLAQSEGV---------------------------DYYKIDLDRCNHSM
tr|A0A0A7GEG9|A0A0A7GEG9_9EURY      -F---------------GN---------------------------AFTSSDAALIN-VA
tr|A0A101GBX3|A0A101GBX3_9BACT      --------------TIESK---------------------------GVVRRDVAYPE-IE
tr|A0A101GRY1|A0A101GRY1_9FIRM      --------------YVDSK---------------------------GPVRREAHYAE-IE
tr|A0A085LA19|A0A085LA19_9FIRM      -G------------TKHGV---------------------------MPARYSASSTL-GS
tr|A0A142JYV4|A0A142JYV4_9ZZZZ      -T------------TKAGF---------------------------QPMRMANATSN-TA
tr|A0A2C8EFD1|A0A2C8EFD1_9BACT      -A------------TKHGF---------------------------QPMRMANATAN-CA
tr|A0A142JYV8|A0A142JYV8_9ZZZZ      -T------------TKKGF---------------------------QPMRMANATIN-CA
tr|A0A142JYV6|A0A142JYV6_9ZZZZ      -T------------TKRGF---------------------------QPMRMANATAN-CA
tr|A0A142JYV7|A0A142JYV7_9ZZZZ      -T------------TKKGF---------------------------QPMRMANATAN-CA
tr|W6CHK3|W6CHK3_9DELT              -T------------TKRGF---------------------------QPMRMASATAN-CA
tr|A0A099TEH5|A0A099TEH5_9DELT      -T------------TKRGF---------------------------QPMRMASATAN-CA
tr|M9T4V0|M9T4V0_9BACT              -T------------TKAGT---------------------------QPYRMATATAN-CA
tr|K7XH43|K7XH43_9BACT              -T------------TKHGA---------------------------QPFRMASATAN-TA
tr|A0A142JYV5|A0A142JYV5_9ZZZZ      -T------------TKNGF---------------------------QPMRMASATAN-MA
tr|A0A094K1W7|A0A094K1W7_9DELT      -T------------TKHGF---------------------------QPMRMASATAN-MA
tr|K7WP62|K7WP62_9BACT              -T------------TKHGF---------------------------QSMRMASATAN-CA
tr|D8WZ05|D8WZ05_9DELT              -T------------TKHGF---------------------------QPFRMASATAN-CA
tr|B0CN00|B0CN00_9DELT              -T------------TKNGV---------------------------QPFRMASATAN-CA
tr|B8FF75|B8FF75_DESAA              -T------------TKNGV---------------------------QPFRMASATAN-CA
tr|B8FEM4|B8FEM4_DESAA              -T------------TKHGV---------------------------QPMRMASATAN-CA
tr|B0CMZ9|B0CMZ9_9DELT              -T------------TKHGV---------------------------QPMRMASATAN-CA
tr|M9TCC2|M9TCC2_9BACT              -P------------TKHGN---------------------------QPFRMASATAN-CA
tr|M9TCD0|M9TCD0_9BACT              -P------------TKHGN---------------------------QPFRMASATAN-CA
tr|M9T6T1|M9T6T1_9BACT              -P------------TKHGN---------------------------QPFRMASATAN-CA
tr|M9T778|M9T778_9BACT              -P------------TKHGN---------------------------QPFRMASATAN-CA
tr|M9TAN7|M9TAN7_9BACT              -P------------TKHGN---------------------------QPFRMASATAN-CA
tr|M9T734|M9T734_9BACT              -P------------TKHGN---------------------------QPFRMASATAN-CA
tr|M9T740|M9T740_9BACT              -P------------TKHGN---------------------------QPFRMASATAN-CA
tr|M9T6R5|M9T6R5_9BACT              -P------------TKHGN---------------------------QPFRMASATAN-CA
tr|M9T6P1|M9T6P1_9BACT              -P------------TKHGN---------------------------QPFRMASATAN-CA
tr|M9T6S4|M9T6S4_9BACT              -P------------TKHGN---------------------------QPFRMASATAN-CA
tr|M9T6S9|M9T6S9_9BACT              -P------------TKHGN---------------------------QPFRMASATAN-CA
tr|M9TAL9|M9TAL9_9BACT              -P------------TKHGN---------------------------QPFRMASATAN-CA
tr|M9T6Q7|M9T6Q7_9BACT              -P------------TKHGN---------------------------QPFRMASATAD-CA
tr|M9T760|M9T760_9BACT              -P------------TKHGN---------------------------QPFRMASATAN-CA
tr|M9TAP4|M9TAP4_9BACT              -P------------TKHGN---------------------------QPFRMASATAN-CA
tr|M9TCA0|M9TCA0_9BACT              -P------------TKHGN---------------------------QPFRMASATAN-CA
tr|M9TCD4|M9TCD4_9BACT              -P------------TKHGY---------------------------QPFRMASATAN-CA
tr|M9T4U5|M9T4U5_9BACT              -P------------TKHGN---------------------------QPFRMAAATAN-CA
                                                                                                

tr|A0A2C8F4Y7|A0A2C8F4Y7_9BACT      RGVAYHL-----RTVLRRMGH----PDEDHLHHPRAPGEPRADPGAQAHPAAVPVGDF--
tr|S0G636|S0G636_9DELT              VCVDVCTHDALTFVS-----T---------LKSVEDIFDDVLKDDIFYKSSGGGFTVSG-
tr|A0A0A7GBY1|A0A0A7GBY1_9EURY      ECVKVCMSEAL-----FIYGQ-----DVEPSGILDEIRKD---------AVFYRNSGGGV
tr|B8FF77|B8FF77_DESAA              QCARTCSHSGLVP-----WGTIQTAAEVMK--------EVFSDEPFFRHSGGGLTLSGG-
tr|B8FF78|B8FF78_DESAA              SCVDACPYGALEIT-----GQ---------AMTVEEILDEVESDRPFYENSGGGMTLSG-
tr|B8FEM1|B8FEM1_DESAA              QCAAVCPYGALEIT-----GK---------LLTVKEILDEVESDLPFYKNSGGGMTLSG-
tr|A0A0A7GEG9|A0A0A7GEG9_9EURY      KALEYALNGGQDMVFGYEFGV----KSEKRPQTLDDVISAFREQLAHIVRLVVTGSNIL-
tr|A0A101GBX3|A0A101GBX3_9BACT      KSVEFTLFNGRDPEPGFEWVKSVETGDPTKFKDFEEFYQAWLKQYEWIITKENYFRNMH-
tr|A0A101GRY1|A0A101GRY1_9FIRM      KAMEFTLFNGRDPEPGFEWAKTIETGDPTKFKDFEEFYQAWLKQYMWFTTFEARIRNM--
tr|A0A085LA19|A0A085LA19_9FIRM      KCVELALWNGFNPVFKMQIGP--KTGDPTKMT-FDELFDACIEQFKVIHWEGCKIRNIS-
tr|A0A142JYV4|A0A142JYV4_9ZZZZ      KIIEYVFTSGFDPVVNMQVGA--ETPDCATFTDFEQVYDAWIAQMKHIFSIAVRIMNYT-
tr|A0A2C8EFD1|A0A2C8EFD1_9BACT      KIIEYVFTSGYDRVVNLQIGA--ETPPVESLTTYEQLFDAWVTQMKTIFTILVRPVNRA-
tr|A0A142JYV8|A0A142JYV8_9ZZZZ      KIIEYVFTSGFDPIISMQIGA--ETPDAATFTDFEQVYDAWVTQMKTIFSVLVRAVNAA-
tr|A0A142JYV6|A0A142JYV6_9ZZZZ      KIIEYVFTSGFDPIVNMQIGA--ETPDAATFTDFEQVYDAWVTQMKTIFSVLVRAVNAG-
tr|A0A142JYV7|A0A142JYV7_9ZZZZ      KIIEYVFTSGFDPVVNMQIGA--ETPDAATFTDFEQVYDVWVIQMKTIFSILTRMINAA-
tr|W6CHK3|W6CHK3_9DELT              KIIEYVFTSGFDPAVSMQIGA--ETPDAATFTSFEQVYAAWITQMKTIFSILTRAVNRA-
tr|A0A099TEH5|A0A099TEH5_9DELT      KIMEYVFTSGFDPVVNMQIGA--ETPDAATFTDFDQVYEAWITQMKTIFSILTRAVNRA-
tr|M9T4V0|M9T4V0_9BACT              KTVEYALFNGYDGVVNMQMGP--KTGDARTFTDFEQLFEAWSKQTEWMFSLLTRVVNLA-
tr|K7XH43|K7XH43_9BACT              KIVEYALFNGYDRVVKMQMGP--QTGDARKFTSFEELYAAWVEQMKWLMDILARTINLG-
tr|A0A142JYV5|A0A142JYV5_9ZZZZ      KVVEYALFNGYDKVVNMQMGP--QTGDARNFKSFDELYNAWAEQLKWLMNLLTMSVNFG-
tr|A0A094K1W7|A0A094K1W7_9DELT      KVVEYALFNGYDPIVNMQMGP--QTGDARKFKSFDELYNAWAEQLKWLMNLLTMSVNFG-
tr|K7WP62|K7WP62_9BACT              KIIEYTLHNGYDPVVNMQMGP--ETGDPCEFKDFEELFQAWVKQAEWLMDILVRTVNLG-
tr|D8WZ05|D8WZ05_9DELT              KMIEYALFNGYDPVVNMQMGP--KTGDARKFKSFDELFEAWVKQMEWLTDTLVRTVNLG-
tr|B0CN00|B0CN00_9DELT              KMVEYALHNGYDHVVGMQMGP--QTGDARTFTDFEQLFDAWTRQMQWLLSLLVRTVNLG-
tr|B8FF75|B8FF75_DESAA              KMVEYALHNGYDHVVGMQMGP--QTGDARTFTDFEQLFDAWTRQMQWLLSLLVRTVNLG-
tr|B8FEM4|B8FEM4_DESAA              KMVEYALHNGYDHVVGMQMGP--ETGDAAKFHDFEDLFQAWVKQMEWLTSLLVRTVNLG-
tr|B0CMZ9|B0CMZ9_9DELT              KMVEYALHNGYDHVVGMQMGP--ETGDAAKFHDFEDLFQAWVKQMEWLTSLLVRTVNLG-
tr|M9TCC2|M9TCC2_9BACT              KIVEYALHNGYDHVVGMQMGE--KTGDARKFTDFEQLFEAWVKQMEWLFSLLVRTSNFG-
tr|M9TCD0|M9TCD0_9BACT              KIVEYALHNGYDHVVGMQMGE--KTGDARKFTDFEQLFEAWVKQMEWLFSLLVRTSNFG-
tr|M9T6T1|M9T6T1_9BACT              KIVEYALNNGYDHVVGMQMGP--QTGDARKFTDFEQVFEAWVKQMEWLFSLLVRTSNFG-
tr|M9T778|M9T778_9BACT              KIVEYALNNGYDHVVGMQMGP--QTGDARKFTDFEQVFGAWVKQMEWLFSLLVRTSNFG-
tr|M9TAN7|M9TAN7_9BACT              KIVEYALNNGYDHVVGMQMGP--QTGDARKFTDFEQVFGAWVKQMEWLFSLLVRTSNFG-
tr|M9T734|M9T734_9BACT              KIVEYALNNGYDHVVGMQMGP--QTGDARKFTDFEQVFEAWVKQMEWLFSLLVRTSNFG-
tr|M9T740|M9T740_9BACT              KIVEYALNNGYDHVVGMQMGP--QTGDARKFTDFEQVFEAWVKQMEWLFSLLVRTSNFG-
tr|M9T6R5|M9T6R5_9BACT              KIVEYALNNGYDHVVGMQMGP--PTGDARKFTDFEQVFEAWVKQMEWLFSLLVRTSNFG-
tr|M9T6P1|M9T6P1_9BACT              KIVEYALNNGYDHVVGMQMGP--QTGDARKFTDFEQVFEAWVKQMEWLFSLLVRTSNFG-
tr|M9T6S4|M9T6S4_9BACT              KIVEYALNNGYDHVVGMQMGP--QTGDARKFTDFEQVFEAWVKQMEWLFSLLVRTSNFG-
tr|M9T6S9|M9T6S9_9BACT              KIVEYALNNGYDHVVGMQMGP--QTGDARKFTDFEQVFEAWVKQMEWLFSLLVRTSNFG-
tr|M9TAL9|M9TAL9_9BACT              KIVEYALNNGYDHVVGMQMGP--QTGDARKFTDFEQVFEAWVKQMEWLFSLLVRTSNFG-
tr|M9T6Q7|M9T6Q7_9BACT              KIVEYALNNGYDHVVGMQMGP--QTGDARKFTDFEQVFEAWVKQMEWLFSLLVRTSNFG-
tr|M9T760|M9T760_9BACT              KIVEYALNNGYDHVVGMQMGP--QTGDARKFTDFEQVFEAWVKQMEWLFSLLVRTSNFG-
tr|M9TAP4|M9TAP4_9BACT              KIVEYALNNGYDHVVGMQMGP--QTGDARKFTDFEQVFEAWVKQMEWLFSLLVRTSNFG-
tr|M9TCA0|M9TCA0_9BACT              KIVEYALNNGYDHVVGMQMGP--QTGDARKFTDFEQVFEAWVKQMEWLFSLLVRTSNFG-
tr|M9TCD4|M9TCD4_9BACT              KIVEYALNNGYDHVVGMQMGP--NSGDAREFTDFEQLFQAWVAQMEWLFSTLVRTVNLG-
tr|M9T4U5|M9T4U5_9BACT              KIVEYALNNGYDNVVGVQMGP--RSGDPREFTDFEQVFQVWVQQMEWLFSLLVRTVNFG-
                                                                                                

tr|A0A2C8F4Y7|A0A2C8F4Y7_9BACT      RAVGGERARRA--GA---FHQPWQR-LDHG----IHLGGERGQPGRGEKA----------
tr|S0G636|S0G636_9DELT              --GEPLMHP----DM---TLALLKRAKKEGLNTVLD---------TCGFANWNSSQPILK
tr|A0A0A7GBY1|A0A0A7GBY1_9EURY      TFSGGEPYSQP--DF---LLETLRLCRDEGINTAVDTSGHT--------P-WKNIERTLD
tr|B8FF77|B8FF77_DESAA              EPMAQP-------GFVLALFTLAKKGAEEG-KPIHTALDTCGHA-----P-WEDYARVLP
tr|B8FF78|B8FF78_DESAA              G--EPTAHP----AF---SEKILAGAKARGLHTCLDTNGHCS---------WSVLESLLK
tr|B8FEM1|B8FEM1_DESAA              --GEPTAHP----DF---AEKLLAGAKARG-LHTCLDT----NGYCS----WDILQRLLK
tr|A0A0A7GEG9|A0A0A7GEG9_9EURY      EYANACVKPT---PL---LSLCVEDCFDRG-LDVTEGGAKYNFTGIQAVG-IADVADSLA
tr|A0A101GBX3|A0A101GBX3_9BACT      LEEMENIIRR---PF---VSLLYESCMESG-LDALNDPTIARYSFQSMVG-WVDVIDCLI
tr|A0A101GRY1|A0A101GRY1_9FIRM      ---HVEELGNNRMPF---ISLLYKSCMESG-LDALNDPTISKLSFQSILG-WVDTIDSLA
tr|A0A085LA19|A0A085LA19_9FIRM      RWVEEEI-GR---PM---LSSGWEECIETG-KNAFQRR-EYGNNWLTTFI-WTDGWDAMA
tr|A0A142JYV4|A0A142JYV4_9ZZZZ      RMNSAAFCPR---PY---LSSISQRSVDSG-LDVMDPSISRGNSWITAFT-FVENIDSLA
tr|A0A2C8EFD1|A0A2C8EFD1_9BACT      RILAPKLTPR---PF---LSAISERSVESG-LDVLEPSISRGNAWITAFT-WVENADSLA
tr|A0A142JYV8|A0A142JYV8_9ZZZZ      RTMAPDMTPR---PF---LSAISERSVESG-LDVMTPSLSRGNSWITAFT-WVENADSLA
tr|A0A142JYV6|A0A142JYV6_9ZZZZ      RAYAPFFTPR---PF---LSAISERSVESG-LDVLTPKLSRGNSWITAFT-WVENADSLA
tr|A0A142JYV7|A0A142JYV7_9ZZZZ      RAYAPGLTPR---PF---LSAISERSVESG-LDVMTPSLSRGNSWITAFT-WVENADSLA
tr|W6CHK3|W6CHK3_9DELT              RILGAELTPR---PF---LSAVSERSVESG-LDVLTPSISQGNSWITAFT-WVENADSLA
tr|A0A099TEH5|A0A099TEH5_9DELT      RILAPELTPR---PY---LSAISERSVESG-LDVYEPSISRGNAWITAFT-WVENIDSLA
tr|M9T4V0|M9T4V0_9BACT              RYMQDEMAPR---PF---LSGISERAVENG-IDAVSPIGERGNAWITAFT-WVENPDSLV
tr|K7XH43|K7XH43_9BACT              RVKDPEFYGR---PF---LSAITERAVEMG-IDAVSPEGERGNAWITWFT-WVENVDSLA
tr|A0A142JYV5|A0A142JYV5_9ZZZZ      RAMSPEMCPR---SF---LSAISERSVESG-LDAVSPEGDRGNSWITAFT-WVENIDSLA
tr|A0A094K1W7|A0A094K1W7_9DELT      RVMSPEMCPR---SF---LSSISERCVESG-QDAASPEGDRGNSWITAFT-WVENIDSLA
tr|K7WP62|K7WP62_9BACT              RVKDPEFYGR---PF---LSSISERSLEQG-TDAVSPEGERGNAWVTGFT-WVENADSLA
tr|D8WZ05|D8WZ05_9DELT              RVKDPEFYGR---PF---LSAISERSVEQG-TDIVNPEGERGNSWVTGFT-WVENADSLA
tr|B0CN00|B0CN00_9DELT              RYKDAEFYGR---PL---LSGITERAVERG-IDAVNPEGERGNCWITGFT-WVENADSLA
tr|B8FF75|B8FF75_DESAA              RYKDAEFYGR---PL---LSGITERAVERG-IDAVNPEGERGNCWITGFT-WVENADSLA
tr|B8FEM4|B8FEM4_DESAA              RYKDPEFFGR---PF---LSGMSERSVESG-LDVVSPVGDRGNCWVTAFT-WVENIDSLA
tr|B0CMZ9|B0CMZ9_9DELT              RYKDPEFFGR---PF---LSGMSERSVESG-LDVVSPVGDRGNCWVTAFT-WVENIDSLA
tr|M9TCC2|M9TCC2_9BACT              RYMDPELFGR---PF---LSAICERSVESG-LDIVSPEGERGNAWVTGFT-WVENADSLA
tr|M9TCD0|M9TCD0_9BACT              RYMDPELFGR---PF---LSAICERSVESG-LDIVSPEGERGNAWVTGFT-WVENADSLA
tr|M9T6T1|M9T6T1_9BACT              RYMDPELFGR---PF---LSAICERSVESG-NDIINPEGERGNAWVTGFT-WVENADSLA
tr|M9T778|M9T778_9BACT              RYMDPELFGR---PF---LSAICERSVESG-NDIINPEGERGNAWVTGFT-WVENADSLA
tr|M9TAN7|M9TAN7_9BACT              RYMDPELFGR---PF---LSAICERSVESG-NDIINPEGERGNAWVTGFT-WVENADSLA
tr|M9T734|M9T734_9BACT              RYMDPELFGR---PL---LSAICERSVESG-NDIINPEGERGNAWVTGFT-WVENADSLA
tr|M9T740|M9T740_9BACT              RYMDPELFGR---PF---LSAICERSVESG-NDIINPEGERGNAWVTGST-WVENADSLA
tr|M9T6R5|M9T6R5_9BACT              RYMDPELFGR---PF---LSAICERSVESG-NDIINPEGERGNAWVTGFT-WVENADSLA
tr|M9T6P1|M9T6P1_9BACT              RYMDPELFGR---PF---LSAICERSVESG-NDIINPEGERGNAWVTGFT-WVENADSLA
tr|M9T6S4|M9T6S4_9BACT              RYMDPELFGR---PF---LSAICERSVESG-NDIINPEGERGNAWVTGFT-WVENADSLA
tr|M9T6S9|M9T6S9_9BACT              RYMDPELFGR---PF---LSAICERSVESG-NDIINPEGERGNAWVTGFT-WVENADSLA
tr|M9TAL9|M9TAL9_9BACT              RYMDPELFGR---PF---LSAICERSVESG-NDIINPEGERGNAWVTGFT-WVENADSLA
tr|M9T6Q7|M9T6Q7_9BACT              RYMDPELFGR---PF---LSAICERSVESG-NDIINPEGERGNAWVTGFT-WVENADSLA
tr|M9T760|M9T760_9BACT              RYMDPELFGR---PF---LSAICERSVESG-NDIINPEGERGNAWVTGFT-WVENADSLA
tr|M9TAP4|M9TAP4_9BACT              RYMDPELFGR---PF---LSAICERSVESG-NDIINPEGERGNAWVTGFT-WVENADSLA
tr|M9TCA0|M9TCA0_9BACT              RCMDPELFGR---PF---LSAICERSVESG-NDIINPEGERGNAWVTGFT-WVENADSLA
tr|M9TCD4|M9TCD4_9BACT              RYMDSELYGR---PF---LSATSERSVESG-LDIIDPTGERGNCWITAFT-WVENADSLA
tr|M9T4U5|M9T4U5_9BACT              RFMDPEFYGR---PF---LSGISERSVESG-LDICSPEGERGNAWITAFT-WVENADSLA
                                                                 *                              

tr|A0A2C8F4Y7|A0A2C8F4Y7_9BACT      ---RVPREEVHH--GRAQGGPGEQLGGQG------RDAARLR--EERAKM-------G--
tr|S0G636|S0G636_9DELT              YVDLIMLDIKSL-------DDQKHKKWTGV-----SNQLILENAKKMSQT-------G--
tr|A0A0A7GBY1|A0A0A7GBY1_9EURY      LVNLFLYDLKDYDSARHRLLT-------G------TGNELI--LDNLRKL-------L--
tr|B8FF77|B8FF77_DESAA              LADLVLLDLKHM--DPQP-----HKAYTGA-----TNRLILDNAQKMAEA-------GAV
tr|B8FF78|B8FF78_DESAA              HTDVVLFDLKHT--DPEK-----HKEWTGVDNALIKENLALLVKNRVETWVRIPVIPG--
tr|B8FEM1|B8FEM1_DESAA              YIDIVLFDLKHT--DPEK-----HKQWTGVDNALIMKNLARLTQTGVETWVRIPVIPG--
tr|A0A0A7GEG9|A0A0A7GEG9_9EURY      AMEHAL--KKGY--TLEEIIEACRSDFDG------YEGLQ-SILLSAPKY-------G--
tr|A0A101GBX3|A0A101GBX3_9BACT      GVKYWIYDKKKY--TMEQLLKALKADWEG------YEDMRQDF-RNAPKF-------G--
tr|A0A101GRY1|A0A101GRY1_9FIRM      AVKYLIYDKKKY--TMEELLKALKANWEG------YEDMRQDF-RNAPKF-------G--
tr|A0A085LA19|A0A085LA19_9FIRM      ALKKLVYDEKKY--TMEQVLEMLKVNWEG------YEVERMDFVR-APKW-------G--
tr|A0A142JYV4|A0A142JYV4_9ZZZZ      AIKKLVFDEKKY--TMAELKQAIVDDWQG------HEKMRLDFVNNAPKW-------G--
tr|A0A2C8EFD1|A0A2C8EFD1_9BACT      AVKKLVFEEKKY--TMAELKEALANNWEG------REEMRLDLVRNAPKW-------G--
tr|A0A142JYV8|A0A142JYV8_9ZZZZ      AIKKLVFEEKKY--TMAQLKKAITDDWQG------HEEMRLDFVKNAPKW-------G--
tr|A0A142JYV6|A0A142JYV6_9ZZZZ      AIKKLVFEEKKY--TMAQLKKALADDWQG------HEEMRLDFVKNAPKW-------G--
tr|A0A142JYV7|A0A142JYV7_9ZZZZ      AIKKLVFEEKKY--TMAQLKKAITDDWQG------HEEMRLDFVKNAPKW-------G--
tr|W6CHK3|W6CHK3_9DELT              AIKKLVFEEKKY--TMAELKKALADDWQG------HEEMRLDFVKNAPKW-------G--
tr|A0A099TEH5|A0A099TEH5_9DELT      AIKKLVFEEKKY--TMAQLKKALADDWQG------QEEMRLDFVKNAPKW-------G--
tr|M9T4V0|M9T4V0_9BACT              AVKKLVFDEKKY--TMDQLMDALEANWEG------NEEMRLDFVNRAPKW-------G--
tr|K7XH43|K7XH43_9BACT              AVKKLVFDEKKY--TMDQLITALENDWEG------YEEMRLDFVKNAPKW-------G--
tr|A0A142JYV5|A0A142JYV5_9ZZZZ      AVKKLVFDDKKY--TMDQLITALDTNWEG------YEEMRLDFVKNAPKW-------G--
tr|A0A094K1W7|A0A094K1W7_9DELT      AVKKLVFDDKKY--TMDQLITALEANWEG------FEQMRLDFVKNAPKW-------G--
tr|K7WP62|K7WP62_9BACT              AIKKLIYDEKKY--TMGQLVEALKANWEG------YEEMRLDFVKNAPKW-------G--
tr|D8WZ05|D8WZ05_9DELT              AVKKLVFDEKKY--TMDQLMDALQANWDG------YEEMRLDFVRNAPKW-------G--
tr|B0CN00|B0CN00_9DELT              AVKKLVFDDKKY--TMDQLITALESNWDG------YEQMRLDFVNKAPKW-------G--
tr|B8FF75|B8FF75_DESAA              AVKKLVFDDKKY--TMDQLITALESNWDG------YEQMRLDFVNKAPKW-------G--
tr|B8FEM4|B8FEM4_DESAA              AVKKLVFDDKKY--TMEQLLTALKANWDG------YEEMRLDFVNNAPKW-------G--
tr|B0CMZ9|B0CMZ9_9DELT              AVKKLVFDDKKY--TMEQLLTALKANWDG------YEEMRLDFVNNAPKW-------G--
tr|M9TCC2|M9TCC2_9BACT              AVKKLVFDEKKY--TMEQLVDALETNWEG------CEEMRLDFVKNAPKW-------G--
tr|M9TCD0|M9TCD0_9BACT              AVKKLVFDEKKY--TMEQLVDALETNWEG------CEEMRLDFVKNAPKW-------G--
tr|M9T6T1|M9T6T1_9BACT              AIKKLVFDEKKY--TMEQLIGALEANWEG------YEEMRLEFVKDAPKW-------G--
tr|M9T778|M9T778_9BACT              AIKKLVFDEKKY--TMEQHIDALEANWEG------YEEMRLEFVKDAPKW-------G--
tr|M9TAN7|M9TAN7_9BACT              AIKKLVFDEKKY--TMEQLIDALEANWEG------YEEMRLEFVKDAPKW-------G--
tr|M9T734|M9T734_9BACT              AIKKLVFDEKKY--TMEQLIDALEANWEG------YEEMRLEFVKDAPRW-------G--
tr|M9T740|M9T740_9BACT              AIKKLVFDEKKY--TMEQLIDALEANWEG------YEEMRLEFVKDAPKW-------G--
tr|M9T6R5|M9T6R5_9BACT              AIKKLVFDEKKY--TMEQLIDALEANWEG------YEEMRLEFVKDAPKW-------G--
tr|M9T6P1|M9T6P1_9BACT              VIKKLVFDEKKY--TMEQLIDALEANWEG------YEEMRLEFVKDAPKW-------G--
tr|M9T6S4|M9T6S4_9BACT              AIKKLVFDEKKY--TMEQLIDALEANWEG------YEEMRLEFVKDAPQW-------G--
tr|M9T6S9|M9T6S9_9BACT              AIKKLVFDEKKY--TMEQLIDALEANWEG------YEEMRLEFVKDAPKW-------G--
tr|M9TAL9|M9TAL9_9BACT              AIKKLVFDEKKY--TMEQLIDALEANWEG------YEEMRLEFVKDAPKW-------G--
tr|M9T6Q7|M9T6Q7_9BACT              AIKKLVFDEKKY--TMEQLIDALEANWEG------YEEMRLEFVKDAPKW-------G--
tr|M9T760|M9T760_9BACT              AIKKLVFDEKRY--TMEQLIDALEANWEG------YEEMRLEFVKDAPKW-------G--
tr|M9TAP4|M9TAP4_9BACT              AIKKLVFDEKKY--TMEQLIDALEANWEG------YEEMRLEFVKDAPKW-------G--
tr|M9TCA0|M9TCA0_9BACT              AIKKLVFDEKKY--TMEQLIDALEANWEG------YEEMRLEFVKDAPKW-------G--
tr|M9TCD4|M9TCD4_9BACT              AVKKLVFDDKKY--TMDQLMTALEANWEG------YEEMRLDFVKGAAKW-------G--
tr|M9T4U5|M9T4U5_9BACT              AVKKLVFDDKKY--TMDQLVTAMQANWEG------YEEMRLDFVRNAPKW-------G--
                                                                *                               

tr|A0A2C8F4Y7|A0A2C8F4Y7_9BACT      -----------QR-----------------------------------------------
tr|S0G636|S0G636_9DELT              ---------------------------------------------IPMRLRLPIIHSVNF
tr|A0A0A7GBY1|A0A0A7GBY1_9EURY      -----------PAS-------------------------DVV-VRIPFIPSCNFQSHDDF
tr|B8FF77|B8FF77_DESAA              MRIRVPIIPGVNDN----------------------------------------------
tr|B8FF78|B8FF78_DESAA              -----------FND-----------------------------------------AIQDH
tr|B8FEM1|B8FEM1_DESAA              -----------FND-----------------------------------------SIEDH
tr|A0A0A7GEG9|A0A0A7GEG9_9EURY      -----------NDGEADRYARMVLEVYCDEVARY----RNFRGGRFTAGC----YPMTTN
tr|A0A101GBX3|A0A101GBX3_9BACT      -----------NDDDYADEVMVKATN--DTYWIHRTKTKDRKGYPIFPNQ----LPISRV
tr|A0A101GRY1|A0A101GRY1_9FIRM      -----------NDNDYADEIMVRATDDVFERCKKETPTSDTRDHPVYPNQ----LPVSRM
tr|A0A085LA19|A0A085LA19_9FIRM      -----------NDDDYVDEIVVKAYNRTRDEVLLPCKDWGRSSRGIPTAP----QNIAAY
tr|A0A142JYV4|A0A142JYV4_9ZZZZ      -----------NDDDYVDGIMLRCL---RDIAKFSHELKDPMGNNWPILP----ENVSGN
tr|A0A2C8EFD1|A0A2C8EFD1_9BACT      -----------ND-----------------------------------------------
tr|A0A142JYV8|A0A142JYV8_9ZZZZ      -----------NDDDYVDNIMLRCL---RSCAVFARELRDPMGNTWPILP----ENVSGN
tr|A0A142JYV6|A0A142JYV6_9ZZZZ      -----------NDDDYVDNIMLRCL---RDCAIFGHELKDPMGNNWPILP----ENVSGN
tr|A0A142JYV7|A0A142JYV7_9ZZZZ      -----------NDDDYVDNIMLRCL---RDCAIFGHELKDPMGNNWPILP----ENVSGN
tr|W6CHK3|W6CHK3_9DELT              -----------NDDDYVDKIMLRCL---HDCAVFSHELKDPMGNNWPILP----ENVSGN
tr|A0A099TEH5|A0A099TEH5_9DELT      -----------NDDDYVDNIMLKCL---RDVAVFSHELKDPSGNNWPILP----ENVSGN
tr|M9T4V0|M9T4V0_9BACT              -----------NDD----------------------------------------------
tr|K7XH43|K7XH43_9BACT              -----------ND-----------------------------------------------
tr|A0A142JYV5|A0A142JYV5_9ZZZZ      -----------NDDDYVDDIMLKCL---REAAQFSKVIKDPSGNNWPILP----ENVSGN
tr|A0A094K1W7|A0A094K1W7_9DELT      -----------NDDDYVDDIMLKCL---REAAAFSRVIKDPSGNNWPILP----ENVSGN
tr|K7WP62|K7WP62_9BACT              -----------ND-----------------------------------------------
tr|D8WZ05|D8WZ05_9DELT              -----------NDDDYVDQIMVRCL---EEVARHSKELKDPTGNPWPLLP----ENVSGN
tr|B0CN00|B0CN00_9DELT              -----------NDDDYVDDIMLRCL---RTLAKHSRVMRCTSNNTWPISP----QNVSGN
tr|B8FF75|B8FF75_DESAA              -----------NDDDYVDDIMLRCL---RTLAKHSRVMRCTSNNTWPISP----QNVSGN
tr|B8FEM4|B8FEM4_DESAA              -----------NDDDYVDDIMLRCL---RETARHSRVMKCPSGNSWPILP----ENVSGN
tr|B0CMZ9|B0CMZ9_9DELT              -----------NDDDYVDDIMLRCL---RETARHSRVMKCPSGNSWPILP----ENVSGN
tr|M9TCC2|M9TCC2_9BACT              -----------NDD----------------------------------------------
tr|M9TCD0|M9TCD0_9BACT              -----------NDDD---------------------------------------------
tr|M9T6T1|M9T6T1_9BACT              -----------NDD----------------------------------------------
tr|M9T778|M9T778_9BACT              -----------NDD----------------------------------------------
tr|M9TAN7|M9TAN7_9BACT              -----------NDD----------------------------------------------
tr|M9T734|M9T734_9BACT              -----------NDD----------------------------------------------
tr|M9T740|M9T740_9BACT              -----------NDD----------------------------------------------
tr|M9T6R5|M9T6R5_9BACT              -----------NDD----------------------------------------------
tr|M9T6P1|M9T6P1_9BACT              -----------NDD----------------------------------------------
tr|M9T6S4|M9T6S4_9BACT              -----------NDD----------------------------------------------
tr|M9T6S9|M9T6S9_9BACT              -----------NDD----------------------------------------------
tr|M9TAL9|M9TAL9_9BACT              -----------NDD----------------------------------------------
tr|M9T6Q7|M9T6Q7_9BACT              -----------NDD----------------------------------------------
tr|M9T760|M9T760_9BACT              -----------NDD----------------------------------------------
tr|M9TAP4|M9TAP4_9BACT              -----------NDD----------------------------------------------
tr|M9TCA0|M9TCA0_9BACT              -----------NDD----------------------------------------------
tr|M9TCD4|M9TCD4_9BACT              -----------NDD----------------------------------------------
tr|M9T4U5|M9T4U5_9BACT              -----------NDD----------------------------------------------
                                                                                                

tr|A0A2C8F4Y7|A0A2C8F4Y7_9BACT      ------------------------------------------------------------
tr|S0G636|S0G636_9DELT              WDIQYPKDIVTFARTLGKNICGIDLLP---------------------------------
tr|A0A0A7GBY1|A0A0A7GBY1_9EURY      RAFLDLLLRLDAG--RVDVL----------------------------------------
tr|B8FF77|B8FF77_DESAA              ---------------------------------------------------KENWTATAK
tr|B8FF78|B8FF78_DESAA              KAAALFLSELPGRVARVDLLPYHNWCQD----------------KYGWLGQNWPLGRTEA
tr|B8FEM1|B8FEM1_DESAA              QAAVEFLNGLPGKIHRVDLLPYHNWCQD----------------KYGWLGLDWPLGRVEA
tr|A0A0A7GEG9|A0A0A7GEG9_9EURY      VAFGFMTSALPSGRKQGMSL-NSGVSPSTGMDREGVTAAIKSVSKINYDKLSNGASFTVN
tr|A0A101GBX3|A0A101GBX3_9BACT      WQSAPYMGAGPNGRKRGDQMCDGGINPHPEFDKSGPWARLRSALKVDQAK-QRAYIYNQR
tr|A0A101GRY1|A0A101GRY1_9FIRM      FQCAPAVGALPNGRKRGDQLCDGGINPHADFDKSGAWARLRSATKVDQGR-ARAYIYNQR
tr|A0A085LA19|A0A085LA19_9FIRM      TVAGVLLGALPNGRRLGDTCYDGGCSPGAGLDKKGPTAVLRSVGKIDHVTSHRANLLNQR
tr|A0A142JYV4|A0A142JYV4_9ZZZZ      IHYANIVGALPNGRRRGDALYDGGISPGPGLDKKGPTAVLKSCAKIDHVMDGRAFLLNQR
tr|A0A2C8EFD1|A0A2C8EFD1_9BACT      ------------------------------------------------------------
tr|A0A142JYV8|A0A142JYV8_9ZZZZ      IHYANVVGALPSGRRRGDALYDGGISPGPGLDKKGPTAVLKSCGKIDHISDGRAFLLNQR
tr|A0A142JYV6|A0A142JYV6_9ZZZZ      IHYANVVGALPSGRRRGDALYDGGISPGPGLDKKGPTAVLKSCGKIDHISDGRAFLLNQR
tr|A0A142JYV7|A0A142JYV7_9ZZZZ      IHYANVVGALPSGRRRGDALYDGGISPGPGLDKKGPTAVLKSCGKIDHISDGRAFLLNQR
tr|W6CHK3|W6CHK3_9DELT              IHYANVVGALPSGRRRGDALYDGGISPGPGLDKKGPTAVLKSCGKIDHITDGRAFLLNQR
tr|A0A099TEH5|A0A099TEH5_9DELT      IHYANIVGALPNGRRRGDALYDGGISPGPGLDKKGPTAVLKSCGKIDHITDGRAFLLNQR
tr|M9T4V0|M9T4V0_9BACT              ------------------------------------------------------------
tr|K7XH43|K7XH43_9BACT              ------------------------------------------------------------
tr|A0A142JYV5|A0A142JYV5_9ZZZZ      IHYANIVRALPNGRRLGDALYDGGISPGPGLDKKGPTAVLKSCGKINHITDGRAFLLNQR
tr|A0A094K1W7|A0A094K1W7_9DELT      IHYANIVRALPNGRRLGDALYDGGISPGPGLDKKGPTAVLKSCGKINHITDGRAFLLNQR
tr|K7WP62|K7WP62_9BACT              ------------------------------------------------------------
tr|D8WZ05|D8WZ05_9DELT              IHYANIVGALPNGRKRGDALYDGGISPGPGLDKKGPTAVLKSCGKFDHVRLGRAFLLNQR
tr|B0CN00|B0CN00_9DELT              IHYSSVVGALPNGRRLGDALYDGGISPGPGLDKKGPTAVLKSCGKIDHVGDGRAFLLNQR
tr|B8FF75|B8FF75_DESAA              IHYSSVVGALPNGRRLGDALYDGGISPGPGLDKKGPTAVLKSCGKIDHVGDGRAFLLNQR
tr|B8FEM4|B8FEM4_DESAA              IHYASIVGALPNGRRCGDALYDGGISPGPGLDKKGPSAVLKSCGKIDHVSDGRAFLLNQR
tr|B0CMZ9|B0CMZ9_9DELT              IHYASIVGALPNGRRCGDALYDGGISPGPGLDKKGPSAVLKSCGKIDHVSDGRAFLLNQR
tr|M9TCC2|M9TCC2_9BACT              ------------------------------------------------------------
tr|M9TCD0|M9TCD0_9BACT              ------------------------------------------------------------
tr|M9T6T1|M9T6T1_9BACT              ------------------------------------------------------------
tr|M9T778|M9T778_9BACT              ------------------------------------------------------------
tr|M9TAN7|M9TAN7_9BACT              ------------------------------------------------------------
tr|M9T734|M9T734_9BACT              ------------------------------------------------------------
tr|M9T740|M9T740_9BACT              ------------------------------------------------------------
tr|M9T6R5|M9T6R5_9BACT              ------------------------------------------------------------
tr|M9T6P1|M9T6P1_9BACT              ------------------------------------------------------------
tr|M9T6S4|M9T6S4_9BACT              ------------------------------------------------------------
tr|M9T6S9|M9T6S9_9BACT              ------------------------------------------------------------
tr|M9TAL9|M9TAL9_9BACT              ------------------------------------------------------------
tr|M9T6Q7|M9T6Q7_9BACT              ------------------------------------------------------------
tr|M9T760|M9T760_9BACT              ------------------------------------------------------------
tr|M9TAP4|M9TAP4_9BACT              ------------------------------------------------------------
tr|M9TCA0|M9TCA0_9BACT              ------------------------------------------------------------
tr|M9TCD4|M9TCD4_9BACT              ------------------------------------------------------------
tr|M9T4U5|M9T4U5_9BACT              ------------------------------------------------------------
                                                                                                

tr|A0A2C8F4Y7|A0A2C8F4Y7_9BACT      ------------------------------------------------------------
tr|S0G636|S0G636_9DELT              ------------------FHNFAAKKFGNIGRKGYFDTFPNIFRKEIEDYKDIIRKGGPW
tr|A0A0A7GBY1|A0A0A7GBY1_9EURY      ----------PYHSLSRDKYRWLGREF----FEVKEGPDYREFVEMLGEAG-IDVSVGGY
tr|B8FF77|B8FF77_DESAA              FAASLGDAVQGVDLLPYHPYAGSKYRAFGMEYDFPAGEGYEDARLEP-------------
tr|B8FF78|B8FF78_DESAA              MEPSLLEIPRELYEMSGLEATIGGSGFEGA------------------------------
tr|B8FEM1|B8FEM1_DESAA              MEPSLLEIPKEYYEMSGLKTTIGGSGFEDAN-----------------------------
tr|A0A0A7GEG9|A0A0A7GEG9_9EURY      LDSGILGG-KGTGIIKALIRSFVELGGMHIQFNVLNENVLRKAQEEPEKYRWLLVRVAGW
tr|A0A101GBX3|A0A101GBX3_9BACT      LDYGSLEGDAGLDKFTDFCQTALQEGQNQVQFNFVSNKMLKDAQKHPEKYPYLTVRVSGY
tr|A0A101GRY1|A0A101GRY1_9FIRM      LDASSVEGDVGLSKFADYCWTAMEEGQTQMQFNFVSSELLRDAQKHPEKYPYLTVRVSGY
tr|A0A085LA19|A0A085LA19_9FIRM      LSPTQLVGDKGFELWHNYIKTWHDLRINHVQFNMVDNETLYAAQKEPEKYSELMVRVAGY
tr|A0A142JYV4|A0A142JYV4_9ZZZZ      FSPTQMAGDKGYALWKAYMDTWYKLGIDHLQFNCVSDETLRSAQREPEKYQEVIVRVAGY
tr|A0A2C8EFD1|A0A2C8EFD1_9BACT      ------------------------------------------------------------
tr|A0A142JYV8|A0A142JYV8_9ZZZZ      LSPTQLAGEKGYSLWKAYMDTWYNLGLDHIQFNCVSDETLRSAQREPEKYQEVIVRVAGY
tr|A0A142JYV6|A0A142JYV6_9ZZZZ      LSPTQMAGEKGYSLWKAYMDTWYNLGLDHIQFNCVSDETLRSAQREPEKYQEVIVRVAGY
tr|A0A142JYV7|A0A142JYV7_9ZZZZ      LSPTQMAGEKGYSLWKAYMDTWYNLGLDHIQFNCVSDETLRSAQREPEKYQEVIVRVAGY
tr|W6CHK3|W6CHK3_9DELT              LSPTQLAGEKGYSFWKSYMDTWYNLGLDHIQFNCVSDETLRSAQREPEKYQEVIVRVAGY
tr|A0A099TEH5|A0A099TEH5_9DELT      LSPTQLAGEKGYSLWKSYMDTWYNLGLDHIQFNCVSDETLKSAQREPEKYQEVIVRVAGY
tr|M9T4V0|M9T4V0_9BACT              ------------------------------------------------------------
tr|K7XH43|K7XH43_9BACT              ------------------------------------------------------------
tr|A0A142JYV5|A0A142JYV5_9ZZZZ      LSPTQLSGEKGYQLWRSYMHTWADLGLDHIQFNVIDDATLRSAQREPEKYQEVIVRVAGY
tr|A0A094K1W7|A0A094K1W7_9DELT      LSPTQLSGEKGYQLWRSYMHTWADLGLDHIQFNVIDDTTLRSAQREPEKYQEVIVRVAGY
tr|K7WP62|K7WP62_9BACT              ------------------------------------------------------------
tr|D8WZ05|D8WZ05_9DELT              LSPTQLKGEQGYQLWKAYMRTWADLGLDHVQFNMVDDATLRAAQKDPEKYQEVIVRVAGY
tr|B0CN00|B0CN00_9DELT              LSPTQMAGEKGYQLWRAYMRTWADLGLDHIQFNMVSDKTLRAAQKDPEKYQEVIVRVAGY
tr|B8FF75|B8FF75_DESAA              LSPTQMAGEKGYQLWRAYMRTWADLGLDHIQFNMVSDKTLRAAQKDPEKYQEVIVRVAGY
tr|B8FEM4|B8FEM4_DESAA              LSPTQLAGEKGYQLWKAYIRTWADLGLDHVQFNMVSDETLRAAQKDPEKYSEVIVRVAGY
tr|B0CMZ9|B0CMZ9_9DELT              LSPTQLAGEKGYQLWKAYIRTWADLGLDHVQFNMVSDETLRAAQKDPEKYSEVIVRVAGY
tr|M9TCC2|M9TCC2_9BACT              ------------------------------------------------------------
tr|M9TCD0|M9TCD0_9BACT              ------------------------------------------------------------
tr|M9T6T1|M9T6T1_9BACT              ------------------------------------------------------------
tr|M9T778|M9T778_9BACT              ------------------------------------------------------------
tr|M9TAN7|M9TAN7_9BACT              ------------------------------------------------------------
tr|M9T734|M9T734_9BACT              ------------------------------------------------------------
tr|M9T740|M9T740_9BACT              ------------------------------------------------------------
tr|M9T6R5|M9T6R5_9BACT              ------------------------------------------------------------
tr|M9T6P1|M9T6P1_9BACT              ------------------------------------------------------------
tr|M9T6S4|M9T6S4_9BACT              ------------------------------------------------------------
tr|M9T6S9|M9T6S9_9BACT              ------------------------------------------------------------
tr|M9TAL9|M9TAL9_9BACT              ------------------------------------------------------------
tr|M9T6Q7|M9T6Q7_9BACT              ------------------------------------------------------------
tr|M9T760|M9T760_9BACT              ------------------------------------------------------------
tr|M9TAP4|M9TAP4_9BACT              ------------------------------------------------------------
tr|M9TCA0|M9TCA0_9BACT              ------------------------------------------------------------
tr|M9TCD4|M9TCD4_9BACT              ------------------------------------------------------------
tr|M9T4U5|M9T4U5_9BACT              ------------------------------------------------------------
                                                                                                

tr|A0A2C8F4Y7|A0A2C8F4Y7_9BACT      -------------------------
tr|S0G636|S0G636_9DELT              QTTIGGLIGVQ--------------
tr|A0A0A7GBY1|A0A0A7GBY1_9EURY      F------------------------
tr|B8FF77|B8FF77_DESAA              ------VIDLFLEHVYEVTIGG---
tr|B8FF78|B8FF78_DESAA              -------------------------
tr|B8FEM1|B8FEM1_DESAA              -------------------------
tr|A0A0A7GEG9|A0A0A7GEG9_9EURY      SAYFVELSRNVQDELIARISCRL--
tr|A0A101GBX3|A0A101GBX3_9BACT      NAFFTGLPKFVQEAVISRVEQKL--
tr|A0A101GRY1|A0A101GRY1_9FIRM      NAFFTQLPTFMQDAVASRVEQKL--
tr|A0A085LA19|A0A085LA19_9FIRM      SAHFTGLNKKTQDTIIARNVQTL--
tr|A0A142JYV4|A0A142JYV4_9ZZZZ      SAHFVDISRKTQDNIIQRTIQGLGN
tr|A0A2C8EFD1|A0A2C8EFD1_9BACT      -------------------------
tr|A0A142JYV8|A0A142JYV8_9ZZZZ      SAHFVDISRKTQDNIIQRTVQGIG-
tr|A0A142JYV6|A0A142JYV6_9ZZZZ      SAHFVDISRKTQDNIIQRTVQGI--
tr|A0A142JYV7|A0A142JYV7_9ZZZZ      SAHFVDISRKTQDNIIQRTVQGIG-
tr|W6CHK3|W6CHK3_9DELT              SAHFVDISRKTQDNIIQRTVQGIG-
tr|A0A099TEH5|A0A099TEH5_9DELT      SAHFVDISRKTQDNIIQRTIQGIG-
tr|M9T4V0|M9T4V0_9BACT              -------------------------
tr|K7XH43|K7XH43_9BACT              -------------------------
tr|A0A142JYV5|A0A142JYV5_9ZZZZ      SAHFVDISRKTQDNIIQRTVQGIA-
tr|A0A094K1W7|A0A094K1W7_9DELT      SAHFVDISRKTQDNIIQRTVQGIG-
tr|K7WP62|K7WP62_9BACT              -------------------------
tr|D8WZ05|D8WZ05_9DELT              SAHFVDISRKTQDNIIQRTIQGL--
tr|B0CN00|B0CN00_9DELT              SAHFVDISRKTQDNIIQRTVQGI--
tr|B8FF75|B8FF75_DESAA              SAHFVDISRKTQDNIIQRTVQGI--
tr|B8FEM4|B8FEM4_DESAA              SAHFVDISRKTQDNIIQRTVQGI--
tr|B0CMZ9|B0CMZ9_9DELT              SAHFVDISRKTQDNIIQRTVQGI--
tr|M9TCC2|M9TCC2_9BACT              -------------------------
tr|M9TCD0|M9TCD0_9BACT              -------------------------
tr|M9T6T1|M9T6T1_9BACT              -------------------------
tr|M9T778|M9T778_9BACT              -------------------------
tr|M9TAN7|M9TAN7_9BACT              -------------------------
tr|M9T734|M9T734_9BACT              -------------------------
tr|M9T740|M9T740_9BACT              -------------------------
tr|M9T6R5|M9T6R5_9BACT              -------------------------
tr|M9T6P1|M9T6P1_9BACT              -------------------------
tr|M9T6S4|M9T6S4_9BACT              -------------------------
tr|M9T6S9|M9T6S9_9BACT              -------------------------
tr|M9TAL9|M9TAL9_9BACT              -------------------------
tr|M9T6Q7|M9T6Q7_9BACT              -------------------------
tr|M9T760|M9T760_9BACT              -------------------------
tr|M9TAP4|M9TAP4_9BACT              -------------------------
tr|M9TCA0|M9TCA0_9BACT              -------------------------
tr|M9TCD4|M9TCD4_9BACT              -------------------------
tr|M9T4U5|M9T4U5_9BACT              -------------------------
                                                             
